/*
 * Generated by JasperReports - 9/8/23 4:20 PM
 */
import net.sf.jasperreports.engine.*;
import net.sf.jasperreports.engine.fill.*;

import java.util.*;
import java.math.*;
import java.text.*;
import java.io.*;
import java.net.*;

import net.sf.jasperreports.engine.*;
import java.util.*;
import net.sf.jasperreports.engine.data.*;


/**
 *
 */
public class all_bill_demand_Vellore_1691578219795_808455 extends JREvaluator
{


    /**
     *
     */
    private JRFillParameter parameter_IS_IGNORE_PAGINATION = null;
    private JRFillParameter parameter_REPORT_CONNECTION = null;
    private JRFillParameter parameter_year = null;
    private JRFillParameter parameter_ctxpath = null;
    private JRFillParameter parameter_imgpath = null;
    private JRFillParameter parameter_REPORT_LOCALE = null;
    private JRFillParameter parameter_REPORT_TIME_ZONE = null;
    private JRFillParameter parameter_REPORT_TEMPLATES = null;
    private JRFillParameter parameter_REPORT_MAX_COUNT = null;
    private JRFillParameter parameter_REPORT_SCRIPTLET = null;
    private JRFillParameter parameter_office_id = null;
    private JRFillParameter parameter_REPORT_FILE_RESOLVER = null;
    private JRFillParameter parameter_month = null;
    private JRFillParameter parameter_REPORT_FORMAT_FACTORY = null;
    private JRFillParameter parameter_REPORT_PARAMETERS_MAP = null;
    private JRFillParameter parameter_REPORT_RESOURCE_BUNDLE = null;
    private JRFillParameter parameter_REPORT_DATA_SOURCE = null;
    private JRFillParameter parameter_billsno = null;
    private JRFillParameter parameter_REPORT_CLASS_LOADER = null;
    private JRFillParameter parameter_REPORT_URL_HANDLER_FACTORY = null;
    private JRFillParameter parameter_REPORT_VIRTUALIZER = null;
    private JRFillField field_ADD_CHARGES_WC = null;
    private JRFillField field_MINUS_CHARGES_WC = null;
    private JRFillField field_ADD_CHARGES_INT = null;
    private JRFillField field_coln_maint = null;
    private JRFillField field_INT_RATE = null;
    private JRFillField field_AMT_WORDS = null;
    private JRFillField field_BILLING_ADDRESS2 = null;
    private JRFillField field_ADD_CHARGES_MAINT = null;
    private JRFillField field_BILLING_ADDRESS3 = null;
    private JRFillField field_DMD_FOR_MTH_MC = null;
    private JRFillField field_BILLING_ADDRESS1 = null;
    private JRFillField field_COLN_INT_WC = null;
    private JRFillField field_address_to = null;
    private JRFillField field_REMARKS = null;
    private JRFillField field_BILL_MONTH = null;
    private JRFillField field_BILL_PERIOD_TO = null;
    private JRFillField field_coln_cur_yr_wc = null;
    private JRFillField field_office_id = null;
    private JRFillField field_BILLING_DT = null;
    private JRFillField field_INT_CALC_WC = null;
    private JRFillField field_DIV_BILL_NO = null;
    private JRFillField field_BENEFICIARY_NAME = null;
    private JRFillField field_OB_INT_AMT_WC = null;
    private JRFillField field_BILL_SNO = null;
    private JRFillField field_BILL_PERIOD_FROM = null;
    private JRFillField field_OFFICE_NAME = null;
    private JRFillField field_wc_mth_total = null;
    private JRFillField field_BENEFICIARY_TYPE_ID = null;
    private JRFillField field_BILLING_PIN_CODE = null;
    private JRFillField field_COLN_YESTER_YR_WC = null;
    private JRFillField field_BENEFICIARY_SNO = null;
    private JRFillField field_MINUS_CHARGES_INT = null;
    private JRFillField field_MINUS_CHARGES_MAINT = null;
    private JRFillField field_CB_INT_AMT_WC = null;
    private JRFillField field_ob_cur_yr_wc = null;
    private JRFillField field_MONTH_BILL_AMT = null;
    private JRFillField field_DMD_INT_FOR_MTH_WC = null;
    private JRFillField field_OB_MAINT_CHARGES = null;
    private JRFillField field_CB_CUR_YR_WC = null;
    private JRFillField field_totob = null;
    private JRFillField field_net_consumption = null;
    private JRFillField field_BILL_YEAR = null;
    private JRFillField field_OB_YESTER_YR_WC = null;
    private JRFillVariable variable_PAGE_NUMBER = null;
    private JRFillVariable variable_COLUMN_NUMBER = null;
    private JRFillVariable variable_REPORT_COUNT = null;
    private JRFillVariable variable_PAGE_COUNT = null;
    private JRFillVariable variable_COLUMN_COUNT = null;
    private JRFillVariable variable_int_res = null;
    private JRFillVariable variable_month_int_cal = null;
    private JRFillVariable variable_BAL_INT = null;
    private JRFillVariable variable_BALANCE_WC = null;
    private JRFillVariable variable_mon_int = null;
    private JRFillVariable variable_BALANCE = null;
    private JRFillVariable variable_BALANCE_MC = null;
    private JRFillVariable variable_OUT_PENALTY = null;
    private JRFillVariable variable_TOT_OB = null;
    private JRFillVariable variable_OB = null;
    private JRFillVariable variable_COLN = null;
    private JRFillVariable variable_net_bal = null;
    private JRFillVariable variable_net_value = null;
    private JRFillVariable variable_bal_1 = null;
    private JRFillVariable variable_sum1 = null;
    private JRFillVariable variable_BAL_INT_2 = null;
    private JRFillVariable variable_var = null;
    private JRFillVariable variable_row1_sum = null;
    private JRFillVariable variable_net_sum2 = null;
    private JRFillVariable variable_net_sum3 = null;
    private JRFillVariable variable_net_sum4 = null;
    private JRFillVariable variable_Balance_after_other_charge = null;
    private JRFillVariable variable_net_sum_new = null;
    private JRFillVariable variable_Balance_new = null;
    private JRFillVariable variable_net_sum_1_new = null;
    private JRFillVariable variable_netotheramt = null;
    private JRFillVariable variable_netotheramt_mc = null;
    private JRFillVariable variable_int_amt = null;
    private JRFillVariable variable_int_display = null;
    private JRFillVariable variable_int_display_2 = null;
    private JRFillVariable variable_netotheramt_int = null;
    private JRFillVariable variable_net_tota_other_charges = null;


    /**
     *
     */
    public void customizedInit(
        Map pm,
        Map fm,
        Map vm
        )
    {
        initParams(pm);
        initFields(fm);
        initVars(vm);
    }


    /**
     *
     */
    private void initParams(Map pm)
    {
        parameter_IS_IGNORE_PAGINATION = (JRFillParameter)pm.get("IS_IGNORE_PAGINATION");
        parameter_REPORT_CONNECTION = (JRFillParameter)pm.get("REPORT_CONNECTION");
        parameter_year = (JRFillParameter)pm.get("year");
        parameter_ctxpath = (JRFillParameter)pm.get("ctxpath");
        parameter_imgpath = (JRFillParameter)pm.get("imgpath");
        parameter_REPORT_LOCALE = (JRFillParameter)pm.get("REPORT_LOCALE");
        parameter_REPORT_TIME_ZONE = (JRFillParameter)pm.get("REPORT_TIME_ZONE");
        parameter_REPORT_TEMPLATES = (JRFillParameter)pm.get("REPORT_TEMPLATES");
        parameter_REPORT_MAX_COUNT = (JRFillParameter)pm.get("REPORT_MAX_COUNT");
        parameter_REPORT_SCRIPTLET = (JRFillParameter)pm.get("REPORT_SCRIPTLET");
        parameter_office_id = (JRFillParameter)pm.get("office_id");
        parameter_REPORT_FILE_RESOLVER = (JRFillParameter)pm.get("REPORT_FILE_RESOLVER");
        parameter_month = (JRFillParameter)pm.get("month");
        parameter_REPORT_FORMAT_FACTORY = (JRFillParameter)pm.get("REPORT_FORMAT_FACTORY");
        parameter_REPORT_PARAMETERS_MAP = (JRFillParameter)pm.get("REPORT_PARAMETERS_MAP");
        parameter_REPORT_RESOURCE_BUNDLE = (JRFillParameter)pm.get("REPORT_RESOURCE_BUNDLE");
        parameter_REPORT_DATA_SOURCE = (JRFillParameter)pm.get("REPORT_DATA_SOURCE");
        parameter_billsno = (JRFillParameter)pm.get("billsno");
        parameter_REPORT_CLASS_LOADER = (JRFillParameter)pm.get("REPORT_CLASS_LOADER");
        parameter_REPORT_URL_HANDLER_FACTORY = (JRFillParameter)pm.get("REPORT_URL_HANDLER_FACTORY");
        parameter_REPORT_VIRTUALIZER = (JRFillParameter)pm.get("REPORT_VIRTUALIZER");
    }


    /**
     *
     */
    private void initFields(Map fm)
    {
        field_ADD_CHARGES_WC = (JRFillField)fm.get("ADD_CHARGES_WC");
        field_MINUS_CHARGES_WC = (JRFillField)fm.get("MINUS_CHARGES_WC");
        field_ADD_CHARGES_INT = (JRFillField)fm.get("ADD_CHARGES_INT");
        field_coln_maint = (JRFillField)fm.get("coln_maint");
        field_INT_RATE = (JRFillField)fm.get("INT_RATE");
        field_AMT_WORDS = (JRFillField)fm.get("AMT_WORDS");
        field_BILLING_ADDRESS2 = (JRFillField)fm.get("BILLING_ADDRESS2");
        field_ADD_CHARGES_MAINT = (JRFillField)fm.get("ADD_CHARGES_MAINT");
        field_BILLING_ADDRESS3 = (JRFillField)fm.get("BILLING_ADDRESS3");
        field_DMD_FOR_MTH_MC = (JRFillField)fm.get("DMD_FOR_MTH_MC");
        field_BILLING_ADDRESS1 = (JRFillField)fm.get("BILLING_ADDRESS1");
        field_COLN_INT_WC = (JRFillField)fm.get("COLN_INT_WC");
        field_address_to = (JRFillField)fm.get("address_to");
        field_REMARKS = (JRFillField)fm.get("REMARKS");
        field_BILL_MONTH = (JRFillField)fm.get("BILL_MONTH");
        field_BILL_PERIOD_TO = (JRFillField)fm.get("BILL_PERIOD_TO");
        field_coln_cur_yr_wc = (JRFillField)fm.get("coln_cur_yr_wc");
        field_office_id = (JRFillField)fm.get("office_id");
        field_BILLING_DT = (JRFillField)fm.get("BILLING_DT");
        field_INT_CALC_WC = (JRFillField)fm.get("INT_CALC_WC");
        field_DIV_BILL_NO = (JRFillField)fm.get("DIV_BILL_NO");
        field_BENEFICIARY_NAME = (JRFillField)fm.get("BENEFICIARY_NAME");
        field_OB_INT_AMT_WC = (JRFillField)fm.get("OB_INT_AMT_WC");
        field_BILL_SNO = (JRFillField)fm.get("BILL_SNO");
        field_BILL_PERIOD_FROM = (JRFillField)fm.get("BILL_PERIOD_FROM");
        field_OFFICE_NAME = (JRFillField)fm.get("OFFICE_NAME");
        field_wc_mth_total = (JRFillField)fm.get("wc_mth_total");
        field_BENEFICIARY_TYPE_ID = (JRFillField)fm.get("BENEFICIARY_TYPE_ID");
        field_BILLING_PIN_CODE = (JRFillField)fm.get("BILLING_PIN_CODE");
        field_COLN_YESTER_YR_WC = (JRFillField)fm.get("COLN_YESTER_YR_WC");
        field_BENEFICIARY_SNO = (JRFillField)fm.get("BENEFICIARY_SNO");
        field_MINUS_CHARGES_INT = (JRFillField)fm.get("MINUS_CHARGES_INT");
        field_MINUS_CHARGES_MAINT = (JRFillField)fm.get("MINUS_CHARGES_MAINT");
        field_CB_INT_AMT_WC = (JRFillField)fm.get("CB_INT_AMT_WC");
        field_ob_cur_yr_wc = (JRFillField)fm.get("ob_cur_yr_wc");
        field_MONTH_BILL_AMT = (JRFillField)fm.get("MONTH_BILL_AMT");
        field_DMD_INT_FOR_MTH_WC = (JRFillField)fm.get("DMD_INT_FOR_MTH_WC");
        field_OB_MAINT_CHARGES = (JRFillField)fm.get("OB_MAINT_CHARGES");
        field_CB_CUR_YR_WC = (JRFillField)fm.get("CB_CUR_YR_WC");
        field_totob = (JRFillField)fm.get("totob");
        field_net_consumption = (JRFillField)fm.get("net_consumption");
        field_BILL_YEAR = (JRFillField)fm.get("BILL_YEAR");
        field_OB_YESTER_YR_WC = (JRFillField)fm.get("OB_YESTER_YR_WC");
    }


    /**
     *
     */
    private void initVars(Map vm)
    {
        variable_PAGE_NUMBER = (JRFillVariable)vm.get("PAGE_NUMBER");
        variable_COLUMN_NUMBER = (JRFillVariable)vm.get("COLUMN_NUMBER");
        variable_REPORT_COUNT = (JRFillVariable)vm.get("REPORT_COUNT");
        variable_PAGE_COUNT = (JRFillVariable)vm.get("PAGE_COUNT");
        variable_COLUMN_COUNT = (JRFillVariable)vm.get("COLUMN_COUNT");
        variable_int_res = (JRFillVariable)vm.get("int_res");
        variable_month_int_cal = (JRFillVariable)vm.get("month_int_cal");
        variable_BAL_INT = (JRFillVariable)vm.get("BAL_INT");
        variable_BALANCE_WC = (JRFillVariable)vm.get("BALANCE_WC");
        variable_mon_int = (JRFillVariable)vm.get("mon_int");
        variable_BALANCE = (JRFillVariable)vm.get("BALANCE");
        variable_BALANCE_MC = (JRFillVariable)vm.get("BALANCE_MC");
        variable_OUT_PENALTY = (JRFillVariable)vm.get("OUT_PENALTY");
        variable_TOT_OB = (JRFillVariable)vm.get("TOT_OB");
        variable_OB = (JRFillVariable)vm.get("OB");
        variable_COLN = (JRFillVariable)vm.get("COLN");
        variable_net_bal = (JRFillVariable)vm.get("net_bal");
        variable_net_value = (JRFillVariable)vm.get("net_value");
        variable_bal_1 = (JRFillVariable)vm.get("bal_1");
        variable_sum1 = (JRFillVariable)vm.get("sum1");
        variable_BAL_INT_2 = (JRFillVariable)vm.get("BAL_INT_2");
        variable_var = (JRFillVariable)vm.get("var");
        variable_row1_sum = (JRFillVariable)vm.get("row1_sum");
        variable_net_sum2 = (JRFillVariable)vm.get("net_sum2");
        variable_net_sum3 = (JRFillVariable)vm.get("net_sum3");
        variable_net_sum4 = (JRFillVariable)vm.get("net_sum4");
        variable_Balance_after_other_charge = (JRFillVariable)vm.get("Balance_after_other_charge");
        variable_net_sum_new = (JRFillVariable)vm.get("net_sum_new");
        variable_Balance_new = (JRFillVariable)vm.get("Balance_new");
        variable_net_sum_1_new = (JRFillVariable)vm.get("net_sum_1_new");
        variable_netotheramt = (JRFillVariable)vm.get("netotheramt");
        variable_netotheramt_mc = (JRFillVariable)vm.get("netotheramt_mc");
        variable_int_amt = (JRFillVariable)vm.get("int_amt");
        variable_int_display = (JRFillVariable)vm.get("int_display");
        variable_int_display_2 = (JRFillVariable)vm.get("int_display_2");
        variable_netotheramt_int = (JRFillVariable)vm.get("netotheramt_int");
        variable_net_tota_other_charges = (JRFillVariable)vm.get("net_tota_other_charges");
    }


    /**
     *
     */
    public Object evaluate(int id) throws Throwable
    {
        Object value = null;

        switch (id)
        {
            case 0 : 
            {
                value = (java.lang.Integer)(new Integer(1));//$JR_EXPR_ID=0$
                break;
            }
            case 1 : 
            {
                value = (java.lang.Integer)(new Integer(1));//$JR_EXPR_ID=1$
                break;
            }
            case 2 : 
            {
                value = (java.lang.Integer)(new Integer(1));//$JR_EXPR_ID=2$
                break;
            }
            case 3 : 
            {
                value = (java.lang.Integer)(new Integer(0));//$JR_EXPR_ID=3$
                break;
            }
            case 4 : 
            {
                value = (java.lang.Integer)(new Integer(1));//$JR_EXPR_ID=4$
                break;
            }
            case 5 : 
            {
                value = (java.lang.Integer)(new Integer(0));//$JR_EXPR_ID=5$
                break;
            }
            case 6 : 
            {
                value = (java.lang.Integer)(new Integer(1));//$JR_EXPR_ID=6$
                break;
            }
            case 7 : 
            {
                value = (java.lang.Integer)(new Integer(0));//$JR_EXPR_ID=7$
                break;
            }
            case 8 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_bal_1.getValue()));//$JR_EXPR_ID=8$
                break;
            }
            case 9 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_bal_1.getValue()));//$JR_EXPR_ID=9$
                break;
            }
            case 10 : 
            {
                value = (java.math.BigDecimal)((((java.math.BigDecimal)field_OB_INT_AMT_WC.getValue())).subtract(((java.math.BigDecimal)field_COLN_INT_WC.getValue())));//$JR_EXPR_ID=10$
                break;
            }
            case 11 : 
            {
                value = (java.math.BigDecimal)(new java.math.BigDecimal("0"));//$JR_EXPR_ID=11$
                break;
            }
            case 12 : 
            {
                value = (java.math.BigDecimal)(((((java.math.BigDecimal)field_OB_YESTER_YR_WC.getValue())).add(((java.math.BigDecimal)field_ob_cur_yr_wc.getValue()) ).subtract(((java.math.BigDecimal)field_coln_cur_yr_wc.getValue())).add(((java.math.BigDecimal)field_COLN_YESTER_YR_WC.getValue()))));//$JR_EXPR_ID=12$
                break;
            }
            case 13 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_INT_RATE.getValue()));//$JR_EXPR_ID=13$
                break;
            }
            case 14 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_Balance_after_other_charge.getValue()).add(((java.math.BigDecimal)variable_BALANCE_MC.getValue())).add(((java.math.BigDecimal)field_OB_INT_AMT_WC.getValue())));//$JR_EXPR_ID=14$
                break;
            }
            case 15 : 
            {
                value = (java.math.BigDecimal)(new java.math.BigDecimal("0"));//$JR_EXPR_ID=15$
                break;
            }
            case 16 : 
            {
                value = (java.math.BigDecimal)((((java.math.BigDecimal)field_OB_MAINT_CHARGES.getValue())).subtract(((java.math.BigDecimal)field_coln_maint.getValue())));//$JR_EXPR_ID=16$
                break;
            }
            case 17 : 
            {
                value = (java.math.BigDecimal)(new java.math.BigDecimal("0"));//$JR_EXPR_ID=17$
                break;
            }
            case 18 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_BALANCE.getValue()).add(((java.math.BigDecimal)field_MONTH_BILL_AMT.getValue())));//$JR_EXPR_ID=18$
                break;
            }
            case 19 : 
            {
                value = (java.math.BigDecimal)((((java.math.BigDecimal)field_OB_YESTER_YR_WC.getValue())).add(((java.math.BigDecimal)field_ob_cur_yr_wc.getValue())));//$JR_EXPR_ID=19$
                break;
            }
            case 20 : 
            {
                value = (java.math.BigDecimal)(new java.math.BigDecimal("0"));//$JR_EXPR_ID=20$
                break;
            }
            case 21 : 
            {
                value = (java.math.BigDecimal)((((java.math.BigDecimal)field_ob_cur_yr_wc.getValue())).add(((java.math.BigDecimal)field_OB_YESTER_YR_WC.getValue())).add(((java.math.BigDecimal)field_OB_MAINT_CHARGES.getValue())).add(((java.math.BigDecimal)field_OB_INT_AMT_WC.getValue())));//$JR_EXPR_ID=21$
                break;
            }
            case 22 : 
            {
                value = (java.math.BigDecimal)(new java.math.BigDecimal("0"));//$JR_EXPR_ID=22$
                break;
            }
            case 23 : 
            {
                value = (java.math.BigDecimal)((((java.math.BigDecimal)field_coln_cur_yr_wc.getValue())).add(((java.math.BigDecimal)field_coln_maint.getValue())).add (((java.math.BigDecimal)field_COLN_YESTER_YR_WC.getValue())).add(((java.math.BigDecimal)field_COLN_INT_WC.getValue())));//$JR_EXPR_ID=23$
                break;
            }
            case 24 : 
            {
                value = (java.math.BigDecimal)(new java.math.BigDecimal("0"));//$JR_EXPR_ID=24$
                break;
            }
            case 25 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_sum1.getValue()));//$JR_EXPR_ID=25$
                break;
            }
            case 26 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_BALANCE.getValue()).add(((java.math.BigDecimal)variable_net_bal.getValue())));//$JR_EXPR_ID=26$
                break;
            }
            case 27 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_BALANCE_WC.getValue()).multiply( ((java.math.BigDecimal)variable_mon_int.getValue()) ).divide(new java.math.BigDecimal("100") ));//$JR_EXPR_ID=27$
                break;
            }
            case 28 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_bal_1.getValue()).add( ((java.math.BigDecimal)field_MONTH_BILL_AMT.getValue()) ).add(((java.math.BigDecimal)field_DMD_FOR_MTH_MC.getValue())));//$JR_EXPR_ID=28$
                break;
            }
            case 29 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_MONTH_BILL_AMT.getValue()).add( ((java.math.BigDecimal)variable_bal_1.getValue())).add(((java.math.BigDecimal)field_DMD_FOR_MTH_MC.getValue())));//$JR_EXPR_ID=29$
                break;
            }
            case 30 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_BALANCE.getValue()).add(((java.math.BigDecimal)variable_net_bal.getValue())));//$JR_EXPR_ID=30$
                break;
            }
            case 31 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_MONTH_BILL_AMT.getValue()).add ( ((java.math.BigDecimal)field_DMD_FOR_MTH_MC.getValue()) ).add(((java.math.BigDecimal)field_INT_CALC_WC.getValue())));//$JR_EXPR_ID=31$
                break;
            }
            case 32 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_Balance_after_other_charge.getValue()));//$JR_EXPR_ID=32$
                break;
            }
            case 33 : 
            {
                value = (java.math.BigDecimal)((((java.math.BigDecimal)field_DMD_FOR_MTH_MC.getValue())).add(((java.math.BigDecimal)variable_BALANCE_MC.getValue())));//$JR_EXPR_ID=33$
                break;
            }
            case 34 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_BAL_INT.getValue()));//$JR_EXPR_ID=34$
                break;
            }
            case 35 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_BALANCE_WC.getValue()));//$JR_EXPR_ID=35$
                break;
            }
            case 36 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_Balance_after_other_charge.getValue()).add(  ((java.math.BigDecimal)field_MONTH_BILL_AMT.getValue()) ));//$JR_EXPR_ID=36$
                break;
            }
            case 37 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_Balance_after_other_charge.getValue()).add(((java.math.BigDecimal)variable_BALANCE_MC.getValue())).add(  ( ((java.math.BigDecimal)variable_BAL_INT.getValue()))));//$JR_EXPR_ID=37$
                break;
            }
            case 38 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_Balance_new.getValue()).add(  ((java.math.BigDecimal)variable_row1_sum.getValue())));//$JR_EXPR_ID=38$
                break;
            }
            case 39 : 
            {
                value = (java.math.BigDecimal)((((java.math.BigDecimal)field_ADD_CHARGES_WC.getValue())).subtract( ((java.math.BigDecimal)field_MINUS_CHARGES_WC.getValue())));//$JR_EXPR_ID=39$
                break;
            }
            case 40 : 
            {
                value = (java.math.BigDecimal)((((java.math.BigDecimal)field_ADD_CHARGES_MAINT.getValue())).subtract( ((java.math.BigDecimal)field_MINUS_CHARGES_MAINT.getValue())));//$JR_EXPR_ID=40$
                break;
            }
            case 41 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_INT_CALC_WC.getValue()).multiply(new java.math.BigDecimal("100")).divide( ((java.math.BigDecimal)field_INT_RATE.getValue())));//$JR_EXPR_ID=41$
                break;
            }
            case 42 : 
            {
                value = (java.lang.String)("<<Penalty @"+((java.math.BigDecimal)field_INT_RATE.getValue())+"% for Rs.");//$JR_EXPR_ID=42$
                break;
            }
            case 43 : 
            {
                value = (java.lang.String)(">>"+((java.math.BigDecimal)field_INT_CALC_WC.getValue()));//$JR_EXPR_ID=43$
                break;
            }
            case 44 : 
            {
                value = (java.math.BigDecimal)((((java.math.BigDecimal)field_ADD_CHARGES_INT.getValue())).subtract( ((java.math.BigDecimal)field_MINUS_CHARGES_INT.getValue())));//$JR_EXPR_ID=44$
                break;
            }
            case 45 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_netotheramt.getValue()).add(((java.math.BigDecimal)variable_netotheramt_int.getValue())));//$JR_EXPR_ID=45$
                break;
            }
            case 46 : 
            {
                value = (java.lang.String)("Bill of cost water supplied during the month ending " + ((java.lang.String)field_BILL_MONTH.getValue()) + " / " + ((java.math.BigDecimal)field_BILL_YEAR.getValue()));//$JR_EXPR_ID=46$
                break;
            }
            case 47 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_imgpath.getValue())+"twademblem.gif");//$JR_EXPR_ID=47$
                break;
            }
            case 48 : 
            {
                value = (java.lang.String)(((java.lang.String)field_BILLING_ADDRESS1.getValue()));//$JR_EXPR_ID=48$
                break;
            }
            case 49 : 
            {
                value = (java.lang.String)(((java.lang.String)field_BILLING_ADDRESS2.getValue()));//$JR_EXPR_ID=49$
                break;
            }
            case 50 : 
            {
                value = (java.lang.String)(((java.lang.String)field_BILLING_ADDRESS3.getValue()));//$JR_EXPR_ID=50$
                break;
            }
            case 51 : 
            {
                value = (java.lang.String)(((java.lang.String)field_BILLING_PIN_CODE.getValue()));//$JR_EXPR_ID=51$
                break;
            }
            case 52 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_MONTH_BILL_AMT.getValue()));//$JR_EXPR_ID=52$
                break;
            }
            case 53 : 
            {
                value = (java.lang.String)("The amount should be sent by Local Bank Cheque (Subject to Realisation) or DD in favour of Executive Engineer, TWAD    Board, " + ((java.lang.String)field_OFFICE_NAME.getValue()));//$JR_EXPR_ID=53$
                break;
            }
            case 54 : 
            {
                value = (java.lang.String)(((java.lang.String)field_OFFICE_NAME.getValue()));//$JR_EXPR_ID=54$
                break;
            }
            case 55 : 
            {
                value = (java.lang.String)(((java.lang.String)field_AMT_WORDS.getValue())+" Only");//$JR_EXPR_ID=55$
                break;
            }
            case 56 : 
            {
                value = (java.lang.Object)(((java.math.BigDecimal)field_BENEFICIARY_SNO.getValue()));//$JR_EXPR_ID=56$
                break;
            }
            case 57 : 
            {
                value = (java.sql.Connection)(((java.sql.Connection)parameter_REPORT_CONNECTION.getValue()));//$JR_EXPR_ID=57$
                break;
            }
            case 58 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_ctxpath.getValue()) + "/offices.jasper");//$JR_EXPR_ID=58$
                break;
            }
            case 59 : 
            {
                value = (java.lang.Object)(((java.lang.String)field_BILL_MONTH.getValue()));//$JR_EXPR_ID=59$
                break;
            }
            case 60 : 
            {
                value = (java.lang.Object)(((java.math.BigDecimal)field_BILL_YEAR.getValue()));//$JR_EXPR_ID=60$
                break;
            }
            case 61 : 
            {
                value = (java.lang.Object)(((java.math.BigDecimal)field_BILL_SNO.getValue()));//$JR_EXPR_ID=61$
                break;
            }
            case 62 : 
            {
                value = (java.sql.Connection)(((java.sql.Connection)parameter_REPORT_CONNECTION.getValue()));//$JR_EXPR_ID=62$
                break;
            }
            case 63 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_ctxpath.getValue()) + "all_Bill_Demand_2.jasper");//$JR_EXPR_ID=63$
                break;
            }
            case 64 : 
            {
                value = (java.lang.Object)(((java.lang.String)field_BILL_MONTH.getValue()));//$JR_EXPR_ID=64$
                break;
            }
            case 65 : 
            {
                value = (java.lang.Object)(((java.math.BigDecimal)field_BILL_YEAR.getValue()));//$JR_EXPR_ID=65$
                break;
            }
            case 66 : 
            {
                value = (java.lang.Object)(((java.lang.String)parameter_ctxpath.getValue()));//$JR_EXPR_ID=66$
                break;
            }
            case 67 : 
            {
                value = (java.lang.Object)(((java.math.BigDecimal)field_BILL_SNO.getValue()));//$JR_EXPR_ID=67$
                break;
            }
            case 68 : 
            {
                value = (java.sql.Connection)(((java.sql.Connection)parameter_REPORT_CONNECTION.getValue()));//$JR_EXPR_ID=68$
                break;
            }
            case 69 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_ctxpath.getValue()) + "all_bill_demand_subreport0.jasper");//$JR_EXPR_ID=69$
                break;
            }
            case 70 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_BAL_INT.getValue()));//$JR_EXPR_ID=70$
                break;
            }
            case 71 : 
            {
                value = (java.math.BigDecimal)((((java.math.BigDecimal)field_coln_maint.getValue())));//$JR_EXPR_ID=71$
                break;
            }
            case 72 : 
            {
                value = (java.math.BigDecimal)((((java.math.BigDecimal)field_coln_cur_yr_wc.getValue())).add(((java.math.BigDecimal)field_COLN_YESTER_YR_WC.getValue())));//$JR_EXPR_ID=72$
                break;
            }
            case 73 : 
            {
                value = (java.math.BigDecimal)((((java.math.BigDecimal)field_OB_MAINT_CHARGES.getValue())));//$JR_EXPR_ID=73$
                break;
            }
            case 74 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_MONTH_BILL_AMT.getValue()));//$JR_EXPR_ID=74$
                break;
            }
            case 75 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_Balance_after_other_charge.getValue()));//$JR_EXPR_ID=75$
                break;
            }
            case 76 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_BALANCE_MC.getValue()));//$JR_EXPR_ID=76$
                break;
            }
            case 77 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_TOT_OB.getValue()));//$JR_EXPR_ID=77$
                break;
            }
            case 78 : 
            {
                value = (java.math.BigDecimal)((((java.math.BigDecimal)field_OB_INT_AMT_WC.getValue())));//$JR_EXPR_ID=78$
                break;
            }
            case 79 : 
            {
                value = (java.math.BigDecimal)((((java.math.BigDecimal)field_COLN_INT_WC.getValue())));//$JR_EXPR_ID=79$
                break;
            }
            case 80 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_INT_CALC_WC.getValue()));//$JR_EXPR_ID=80$
                break;
            }
            case 81 : 
            {
                value = (java.math.BigDecimal)((((java.math.BigDecimal)field_DMD_FOR_MTH_MC.getValue())));//$JR_EXPR_ID=81$
                break;
            }
            case 82 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_net_sum_new.getValue()).add(((java.math.BigDecimal)variable_netotheramt.getValue())));//$JR_EXPR_ID=82$
                break;
            }
            case 83 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_net_sum3.getValue()).add(((java.math.BigDecimal)variable_netotheramt_mc.getValue())));//$JR_EXPR_ID=83$
                break;
            }
            case 84 : 
            {
                value = (java.math.BigDecimal)((((java.math.BigDecimal)variable_BAL_INT.getValue()).add(((java.math.BigDecimal)field_INT_CALC_WC.getValue()))).add(((java.math.BigDecimal)variable_netotheramt_int.getValue())));//$JR_EXPR_ID=84$
                break;
            }
            case 85 : 
            {
                value = (java.lang.String)(((java.lang.String)field_OFFICE_NAME.getValue()));//$JR_EXPR_ID=85$
                break;
            }
            case 86 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_Balance_new.getValue()));//$JR_EXPR_ID=86$
                break;
            }
            case 87 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_OB.getValue()));//$JR_EXPR_ID=87$
                break;
            }
            case 88 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_COLN.getValue()));//$JR_EXPR_ID=88$
                break;
            }
            case 89 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_row1_sum.getValue()));//$JR_EXPR_ID=89$
                break;
            }
            case 90 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_net_sum_1_new.getValue()) .add(((java.math.BigDecimal)variable_netotheramt.getValue())).add(((java.math.BigDecimal)variable_netotheramt_mc.getValue())).add(((java.math.BigDecimal)variable_netotheramt_int.getValue())));//$JR_EXPR_ID=90$
                break;
            }
            case 91 : 
            {
                value = (java.lang.String)(" Note :" + ((java.lang.String)field_REMARKS.getValue()));//$JR_EXPR_ID=91$
                break;
            }
            case 92 : 
            {
                value = (java.lang.String)(" Add : " + ((java.math.BigDecimal)field_ADD_CHARGES_WC.getValue()));//$JR_EXPR_ID=92$
                break;
            }
            case 93 : 
            {
                value = (java.lang.String)("Subtract:  "+ ((java.math.BigDecimal)field_MINUS_CHARGES_WC.getValue()));//$JR_EXPR_ID=93$
                break;
            }
            case 94 : 
            {
                value = (java.lang.String)(""+((java.lang.String)field_BILL_MONTH.getValue())+((java.math.BigDecimal)field_BILL_YEAR.getValue())+((java.lang.String)field_DIV_BILL_NO.getValue()));//$JR_EXPR_ID=94$
                break;
            }
            case 95 : 
            {
                value = (java.lang.String)(((java.lang.String)field_BILLING_DT.getValue()));//$JR_EXPR_ID=95$
                break;
            }
            case 96 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_netotheramt.getValue()));//$JR_EXPR_ID=96$
                break;
            }
            case 97 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_net_tota_other_charges.getValue()));//$JR_EXPR_ID=97$
                break;
            }
            case 98 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_netotheramt_mc.getValue()));//$JR_EXPR_ID=98$
                break;
            }
            case 99 : 
            {
                value = (java.lang.String)(((java.lang.String)field_BENEFICIARY_NAME.getValue()));//$JR_EXPR_ID=99$
                break;
            }
           default :
           {
               value = evaluate1(id);
           }
        }
        
        return value;
    }


    /**
     *
     */
    private Object evaluate1(int id) throws Throwable
    {
        Object value = null;

        switch (id)
        {
            case 100 : 
            {
                value = (java.lang.String)(((java.lang.String)variable_int_display.getValue()));//$JR_EXPR_ID=100$
                break;
            }
            case 101 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_int_amt.getValue()));//$JR_EXPR_ID=101$
                break;
            }
            case 102 : 
            {
                value = (java.lang.String)(((java.lang.String)variable_int_display_2.getValue()));//$JR_EXPR_ID=102$
                break;
            }
            case 103 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_netotheramt_int.getValue()));//$JR_EXPR_ID=103$
                break;
            }
           default :
           {
           }
        }
        
        return value;
    }


    /**
     *
     */
    public Object evaluateOld(int id) throws Throwable
    {
        Object value = null;

        switch (id)
        {
            case 0 : 
            {
                value = (java.lang.Integer)(new Integer(1));//$JR_EXPR_ID=0$
                break;
            }
            case 1 : 
            {
                value = (java.lang.Integer)(new Integer(1));//$JR_EXPR_ID=1$
                break;
            }
            case 2 : 
            {
                value = (java.lang.Integer)(new Integer(1));//$JR_EXPR_ID=2$
                break;
            }
            case 3 : 
            {
                value = (java.lang.Integer)(new Integer(0));//$JR_EXPR_ID=3$
                break;
            }
            case 4 : 
            {
                value = (java.lang.Integer)(new Integer(1));//$JR_EXPR_ID=4$
                break;
            }
            case 5 : 
            {
                value = (java.lang.Integer)(new Integer(0));//$JR_EXPR_ID=5$
                break;
            }
            case 6 : 
            {
                value = (java.lang.Integer)(new Integer(1));//$JR_EXPR_ID=6$
                break;
            }
            case 7 : 
            {
                value = (java.lang.Integer)(new Integer(0));//$JR_EXPR_ID=7$
                break;
            }
            case 8 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_bal_1.getOldValue()));//$JR_EXPR_ID=8$
                break;
            }
            case 9 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_bal_1.getOldValue()));//$JR_EXPR_ID=9$
                break;
            }
            case 10 : 
            {
                value = (java.math.BigDecimal)((((java.math.BigDecimal)field_OB_INT_AMT_WC.getOldValue())).subtract(((java.math.BigDecimal)field_COLN_INT_WC.getOldValue())));//$JR_EXPR_ID=10$
                break;
            }
            case 11 : 
            {
                value = (java.math.BigDecimal)(new java.math.BigDecimal("0"));//$JR_EXPR_ID=11$
                break;
            }
            case 12 : 
            {
                value = (java.math.BigDecimal)(((((java.math.BigDecimal)field_OB_YESTER_YR_WC.getOldValue())).add(((java.math.BigDecimal)field_ob_cur_yr_wc.getOldValue()) ).subtract(((java.math.BigDecimal)field_coln_cur_yr_wc.getOldValue())).add(((java.math.BigDecimal)field_COLN_YESTER_YR_WC.getOldValue()))));//$JR_EXPR_ID=12$
                break;
            }
            case 13 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_INT_RATE.getOldValue()));//$JR_EXPR_ID=13$
                break;
            }
            case 14 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_Balance_after_other_charge.getOldValue()).add(((java.math.BigDecimal)variable_BALANCE_MC.getOldValue())).add(((java.math.BigDecimal)field_OB_INT_AMT_WC.getOldValue())));//$JR_EXPR_ID=14$
                break;
            }
            case 15 : 
            {
                value = (java.math.BigDecimal)(new java.math.BigDecimal("0"));//$JR_EXPR_ID=15$
                break;
            }
            case 16 : 
            {
                value = (java.math.BigDecimal)((((java.math.BigDecimal)field_OB_MAINT_CHARGES.getOldValue())).subtract(((java.math.BigDecimal)field_coln_maint.getOldValue())));//$JR_EXPR_ID=16$
                break;
            }
            case 17 : 
            {
                value = (java.math.BigDecimal)(new java.math.BigDecimal("0"));//$JR_EXPR_ID=17$
                break;
            }
            case 18 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_BALANCE.getOldValue()).add(((java.math.BigDecimal)field_MONTH_BILL_AMT.getOldValue())));//$JR_EXPR_ID=18$
                break;
            }
            case 19 : 
            {
                value = (java.math.BigDecimal)((((java.math.BigDecimal)field_OB_YESTER_YR_WC.getOldValue())).add(((java.math.BigDecimal)field_ob_cur_yr_wc.getOldValue())));//$JR_EXPR_ID=19$
                break;
            }
            case 20 : 
            {
                value = (java.math.BigDecimal)(new java.math.BigDecimal("0"));//$JR_EXPR_ID=20$
                break;
            }
            case 21 : 
            {
                value = (java.math.BigDecimal)((((java.math.BigDecimal)field_ob_cur_yr_wc.getOldValue())).add(((java.math.BigDecimal)field_OB_YESTER_YR_WC.getOldValue())).add(((java.math.BigDecimal)field_OB_MAINT_CHARGES.getOldValue())).add(((java.math.BigDecimal)field_OB_INT_AMT_WC.getOldValue())));//$JR_EXPR_ID=21$
                break;
            }
            case 22 : 
            {
                value = (java.math.BigDecimal)(new java.math.BigDecimal("0"));//$JR_EXPR_ID=22$
                break;
            }
            case 23 : 
            {
                value = (java.math.BigDecimal)((((java.math.BigDecimal)field_coln_cur_yr_wc.getOldValue())).add(((java.math.BigDecimal)field_coln_maint.getOldValue())).add (((java.math.BigDecimal)field_COLN_YESTER_YR_WC.getOldValue())).add(((java.math.BigDecimal)field_COLN_INT_WC.getOldValue())));//$JR_EXPR_ID=23$
                break;
            }
            case 24 : 
            {
                value = (java.math.BigDecimal)(new java.math.BigDecimal("0"));//$JR_EXPR_ID=24$
                break;
            }
            case 25 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_sum1.getOldValue()));//$JR_EXPR_ID=25$
                break;
            }
            case 26 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_BALANCE.getOldValue()).add(((java.math.BigDecimal)variable_net_bal.getOldValue())));//$JR_EXPR_ID=26$
                break;
            }
            case 27 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_BALANCE_WC.getOldValue()).multiply( ((java.math.BigDecimal)variable_mon_int.getOldValue()) ).divide(new java.math.BigDecimal("100") ));//$JR_EXPR_ID=27$
                break;
            }
            case 28 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_bal_1.getOldValue()).add( ((java.math.BigDecimal)field_MONTH_BILL_AMT.getOldValue()) ).add(((java.math.BigDecimal)field_DMD_FOR_MTH_MC.getOldValue())));//$JR_EXPR_ID=28$
                break;
            }
            case 29 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_MONTH_BILL_AMT.getOldValue()).add( ((java.math.BigDecimal)variable_bal_1.getOldValue())).add(((java.math.BigDecimal)field_DMD_FOR_MTH_MC.getOldValue())));//$JR_EXPR_ID=29$
                break;
            }
            case 30 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_BALANCE.getOldValue()).add(((java.math.BigDecimal)variable_net_bal.getOldValue())));//$JR_EXPR_ID=30$
                break;
            }
            case 31 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_MONTH_BILL_AMT.getOldValue()).add ( ((java.math.BigDecimal)field_DMD_FOR_MTH_MC.getOldValue()) ).add(((java.math.BigDecimal)field_INT_CALC_WC.getOldValue())));//$JR_EXPR_ID=31$
                break;
            }
            case 32 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_Balance_after_other_charge.getOldValue()));//$JR_EXPR_ID=32$
                break;
            }
            case 33 : 
            {
                value = (java.math.BigDecimal)((((java.math.BigDecimal)field_DMD_FOR_MTH_MC.getOldValue())).add(((java.math.BigDecimal)variable_BALANCE_MC.getOldValue())));//$JR_EXPR_ID=33$
                break;
            }
            case 34 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_BAL_INT.getOldValue()));//$JR_EXPR_ID=34$
                break;
            }
            case 35 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_BALANCE_WC.getOldValue()));//$JR_EXPR_ID=35$
                break;
            }
            case 36 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_Balance_after_other_charge.getOldValue()).add(  ((java.math.BigDecimal)field_MONTH_BILL_AMT.getOldValue()) ));//$JR_EXPR_ID=36$
                break;
            }
            case 37 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_Balance_after_other_charge.getOldValue()).add(((java.math.BigDecimal)variable_BALANCE_MC.getOldValue())).add(  ( ((java.math.BigDecimal)variable_BAL_INT.getOldValue()))));//$JR_EXPR_ID=37$
                break;
            }
            case 38 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_Balance_new.getOldValue()).add(  ((java.math.BigDecimal)variable_row1_sum.getOldValue())));//$JR_EXPR_ID=38$
                break;
            }
            case 39 : 
            {
                value = (java.math.BigDecimal)((((java.math.BigDecimal)field_ADD_CHARGES_WC.getOldValue())).subtract( ((java.math.BigDecimal)field_MINUS_CHARGES_WC.getOldValue())));//$JR_EXPR_ID=39$
                break;
            }
            case 40 : 
            {
                value = (java.math.BigDecimal)((((java.math.BigDecimal)field_ADD_CHARGES_MAINT.getOldValue())).subtract( ((java.math.BigDecimal)field_MINUS_CHARGES_MAINT.getOldValue())));//$JR_EXPR_ID=40$
                break;
            }
            case 41 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_INT_CALC_WC.getOldValue()).multiply(new java.math.BigDecimal("100")).divide( ((java.math.BigDecimal)field_INT_RATE.getOldValue())));//$JR_EXPR_ID=41$
                break;
            }
            case 42 : 
            {
                value = (java.lang.String)("<<Penalty @"+((java.math.BigDecimal)field_INT_RATE.getOldValue())+"% for Rs.");//$JR_EXPR_ID=42$
                break;
            }
            case 43 : 
            {
                value = (java.lang.String)(">>"+((java.math.BigDecimal)field_INT_CALC_WC.getOldValue()));//$JR_EXPR_ID=43$
                break;
            }
            case 44 : 
            {
                value = (java.math.BigDecimal)((((java.math.BigDecimal)field_ADD_CHARGES_INT.getOldValue())).subtract( ((java.math.BigDecimal)field_MINUS_CHARGES_INT.getOldValue())));//$JR_EXPR_ID=44$
                break;
            }
            case 45 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_netotheramt.getOldValue()).add(((java.math.BigDecimal)variable_netotheramt_int.getOldValue())));//$JR_EXPR_ID=45$
                break;
            }
            case 46 : 
            {
                value = (java.lang.String)("Bill of cost water supplied during the month ending " + ((java.lang.String)field_BILL_MONTH.getOldValue()) + " / " + ((java.math.BigDecimal)field_BILL_YEAR.getOldValue()));//$JR_EXPR_ID=46$
                break;
            }
            case 47 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_imgpath.getValue())+"twademblem.gif");//$JR_EXPR_ID=47$
                break;
            }
            case 48 : 
            {
                value = (java.lang.String)(((java.lang.String)field_BILLING_ADDRESS1.getOldValue()));//$JR_EXPR_ID=48$
                break;
            }
            case 49 : 
            {
                value = (java.lang.String)(((java.lang.String)field_BILLING_ADDRESS2.getOldValue()));//$JR_EXPR_ID=49$
                break;
            }
            case 50 : 
            {
                value = (java.lang.String)(((java.lang.String)field_BILLING_ADDRESS3.getOldValue()));//$JR_EXPR_ID=50$
                break;
            }
            case 51 : 
            {
                value = (java.lang.String)(((java.lang.String)field_BILLING_PIN_CODE.getOldValue()));//$JR_EXPR_ID=51$
                break;
            }
            case 52 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_MONTH_BILL_AMT.getOldValue()));//$JR_EXPR_ID=52$
                break;
            }
            case 53 : 
            {
                value = (java.lang.String)("The amount should be sent by Local Bank Cheque (Subject to Realisation) or DD in favour of Executive Engineer, TWAD    Board, " + ((java.lang.String)field_OFFICE_NAME.getOldValue()));//$JR_EXPR_ID=53$
                break;
            }
            case 54 : 
            {
                value = (java.lang.String)(((java.lang.String)field_OFFICE_NAME.getOldValue()));//$JR_EXPR_ID=54$
                break;
            }
            case 55 : 
            {
                value = (java.lang.String)(((java.lang.String)field_AMT_WORDS.getOldValue())+" Only");//$JR_EXPR_ID=55$
                break;
            }
            case 56 : 
            {
                value = (java.lang.Object)(((java.math.BigDecimal)field_BENEFICIARY_SNO.getOldValue()));//$JR_EXPR_ID=56$
                break;
            }
            case 57 : 
            {
                value = (java.sql.Connection)(((java.sql.Connection)parameter_REPORT_CONNECTION.getValue()));//$JR_EXPR_ID=57$
                break;
            }
            case 58 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_ctxpath.getValue()) + "/offices.jasper");//$JR_EXPR_ID=58$
                break;
            }
            case 59 : 
            {
                value = (java.lang.Object)(((java.lang.String)field_BILL_MONTH.getOldValue()));//$JR_EXPR_ID=59$
                break;
            }
            case 60 : 
            {
                value = (java.lang.Object)(((java.math.BigDecimal)field_BILL_YEAR.getOldValue()));//$JR_EXPR_ID=60$
                break;
            }
            case 61 : 
            {
                value = (java.lang.Object)(((java.math.BigDecimal)field_BILL_SNO.getOldValue()));//$JR_EXPR_ID=61$
                break;
            }
            case 62 : 
            {
                value = (java.sql.Connection)(((java.sql.Connection)parameter_REPORT_CONNECTION.getValue()));//$JR_EXPR_ID=62$
                break;
            }
            case 63 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_ctxpath.getValue()) + "all_Bill_Demand_2.jasper");//$JR_EXPR_ID=63$
                break;
            }
            case 64 : 
            {
                value = (java.lang.Object)(((java.lang.String)field_BILL_MONTH.getOldValue()));//$JR_EXPR_ID=64$
                break;
            }
            case 65 : 
            {
                value = (java.lang.Object)(((java.math.BigDecimal)field_BILL_YEAR.getOldValue()));//$JR_EXPR_ID=65$
                break;
            }
            case 66 : 
            {
                value = (java.lang.Object)(((java.lang.String)parameter_ctxpath.getValue()));//$JR_EXPR_ID=66$
                break;
            }
            case 67 : 
            {
                value = (java.lang.Object)(((java.math.BigDecimal)field_BILL_SNO.getOldValue()));//$JR_EXPR_ID=67$
                break;
            }
            case 68 : 
            {
                value = (java.sql.Connection)(((java.sql.Connection)parameter_REPORT_CONNECTION.getValue()));//$JR_EXPR_ID=68$
                break;
            }
            case 69 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_ctxpath.getValue()) + "all_bill_demand_subreport0.jasper");//$JR_EXPR_ID=69$
                break;
            }
            case 70 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_BAL_INT.getOldValue()));//$JR_EXPR_ID=70$
                break;
            }
            case 71 : 
            {
                value = (java.math.BigDecimal)((((java.math.BigDecimal)field_coln_maint.getOldValue())));//$JR_EXPR_ID=71$
                break;
            }
            case 72 : 
            {
                value = (java.math.BigDecimal)((((java.math.BigDecimal)field_coln_cur_yr_wc.getOldValue())).add(((java.math.BigDecimal)field_COLN_YESTER_YR_WC.getOldValue())));//$JR_EXPR_ID=72$
                break;
            }
            case 73 : 
            {
                value = (java.math.BigDecimal)((((java.math.BigDecimal)field_OB_MAINT_CHARGES.getOldValue())));//$JR_EXPR_ID=73$
                break;
            }
            case 74 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_MONTH_BILL_AMT.getOldValue()));//$JR_EXPR_ID=74$
                break;
            }
            case 75 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_Balance_after_other_charge.getOldValue()));//$JR_EXPR_ID=75$
                break;
            }
            case 76 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_BALANCE_MC.getOldValue()));//$JR_EXPR_ID=76$
                break;
            }
            case 77 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_TOT_OB.getOldValue()));//$JR_EXPR_ID=77$
                break;
            }
            case 78 : 
            {
                value = (java.math.BigDecimal)((((java.math.BigDecimal)field_OB_INT_AMT_WC.getOldValue())));//$JR_EXPR_ID=78$
                break;
            }
            case 79 : 
            {
                value = (java.math.BigDecimal)((((java.math.BigDecimal)field_COLN_INT_WC.getOldValue())));//$JR_EXPR_ID=79$
                break;
            }
            case 80 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_INT_CALC_WC.getOldValue()));//$JR_EXPR_ID=80$
                break;
            }
            case 81 : 
            {
                value = (java.math.BigDecimal)((((java.math.BigDecimal)field_DMD_FOR_MTH_MC.getOldValue())));//$JR_EXPR_ID=81$
                break;
            }
            case 82 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_net_sum_new.getOldValue()).add(((java.math.BigDecimal)variable_netotheramt.getOldValue())));//$JR_EXPR_ID=82$
                break;
            }
            case 83 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_net_sum3.getOldValue()).add(((java.math.BigDecimal)variable_netotheramt_mc.getOldValue())));//$JR_EXPR_ID=83$
                break;
            }
            case 84 : 
            {
                value = (java.math.BigDecimal)((((java.math.BigDecimal)variable_BAL_INT.getOldValue()).add(((java.math.BigDecimal)field_INT_CALC_WC.getOldValue()))).add(((java.math.BigDecimal)variable_netotheramt_int.getOldValue())));//$JR_EXPR_ID=84$
                break;
            }
            case 85 : 
            {
                value = (java.lang.String)(((java.lang.String)field_OFFICE_NAME.getOldValue()));//$JR_EXPR_ID=85$
                break;
            }
            case 86 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_Balance_new.getOldValue()));//$JR_EXPR_ID=86$
                break;
            }
            case 87 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_OB.getOldValue()));//$JR_EXPR_ID=87$
                break;
            }
            case 88 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_COLN.getOldValue()));//$JR_EXPR_ID=88$
                break;
            }
            case 89 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_row1_sum.getOldValue()));//$JR_EXPR_ID=89$
                break;
            }
            case 90 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_net_sum_1_new.getOldValue()) .add(((java.math.BigDecimal)variable_netotheramt.getOldValue())).add(((java.math.BigDecimal)variable_netotheramt_mc.getOldValue())).add(((java.math.BigDecimal)variable_netotheramt_int.getOldValue())));//$JR_EXPR_ID=90$
                break;
            }
            case 91 : 
            {
                value = (java.lang.String)(" Note :" + ((java.lang.String)field_REMARKS.getOldValue()));//$JR_EXPR_ID=91$
                break;
            }
            case 92 : 
            {
                value = (java.lang.String)(" Add : " + ((java.math.BigDecimal)field_ADD_CHARGES_WC.getOldValue()));//$JR_EXPR_ID=92$
                break;
            }
            case 93 : 
            {
                value = (java.lang.String)("Subtract:  "+ ((java.math.BigDecimal)field_MINUS_CHARGES_WC.getOldValue()));//$JR_EXPR_ID=93$
                break;
            }
            case 94 : 
            {
                value = (java.lang.String)(""+((java.lang.String)field_BILL_MONTH.getOldValue())+((java.math.BigDecimal)field_BILL_YEAR.getOldValue())+((java.lang.String)field_DIV_BILL_NO.getOldValue()));//$JR_EXPR_ID=94$
                break;
            }
            case 95 : 
            {
                value = (java.lang.String)(((java.lang.String)field_BILLING_DT.getOldValue()));//$JR_EXPR_ID=95$
                break;
            }
            case 96 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_netotheramt.getOldValue()));//$JR_EXPR_ID=96$
                break;
            }
            case 97 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_net_tota_other_charges.getOldValue()));//$JR_EXPR_ID=97$
                break;
            }
            case 98 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_netotheramt_mc.getOldValue()));//$JR_EXPR_ID=98$
                break;
            }
            case 99 : 
            {
                value = (java.lang.String)(((java.lang.String)field_BENEFICIARY_NAME.getOldValue()));//$JR_EXPR_ID=99$
                break;
            }
           default :
           {
               value = evaluateOld1(id);
           }
        }
        
        return value;
    }


    /**
     *
     */
    private Object evaluateOld1(int id) throws Throwable
    {
        Object value = null;

        switch (id)
        {
            case 100 : 
            {
                value = (java.lang.String)(((java.lang.String)variable_int_display.getOldValue()));//$JR_EXPR_ID=100$
                break;
            }
            case 101 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_int_amt.getOldValue()));//$JR_EXPR_ID=101$
                break;
            }
            case 102 : 
            {
                value = (java.lang.String)(((java.lang.String)variable_int_display_2.getOldValue()));//$JR_EXPR_ID=102$
                break;
            }
            case 103 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_netotheramt_int.getOldValue()));//$JR_EXPR_ID=103$
                break;
            }
           default :
           {
           }
        }
        
        return value;
    }


    /**
     *
     */
    public Object evaluateEstimated(int id) throws Throwable
    {
        Object value = null;

        switch (id)
        {
            case 0 : 
            {
                value = (java.lang.Integer)(new Integer(1));//$JR_EXPR_ID=0$
                break;
            }
            case 1 : 
            {
                value = (java.lang.Integer)(new Integer(1));//$JR_EXPR_ID=1$
                break;
            }
            case 2 : 
            {
                value = (java.lang.Integer)(new Integer(1));//$JR_EXPR_ID=2$
                break;
            }
            case 3 : 
            {
                value = (java.lang.Integer)(new Integer(0));//$JR_EXPR_ID=3$
                break;
            }
            case 4 : 
            {
                value = (java.lang.Integer)(new Integer(1));//$JR_EXPR_ID=4$
                break;
            }
            case 5 : 
            {
                value = (java.lang.Integer)(new Integer(0));//$JR_EXPR_ID=5$
                break;
            }
            case 6 : 
            {
                value = (java.lang.Integer)(new Integer(1));//$JR_EXPR_ID=6$
                break;
            }
            case 7 : 
            {
                value = (java.lang.Integer)(new Integer(0));//$JR_EXPR_ID=7$
                break;
            }
            case 8 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_bal_1.getEstimatedValue()));//$JR_EXPR_ID=8$
                break;
            }
            case 9 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_bal_1.getEstimatedValue()));//$JR_EXPR_ID=9$
                break;
            }
            case 10 : 
            {
                value = (java.math.BigDecimal)((((java.math.BigDecimal)field_OB_INT_AMT_WC.getValue())).subtract(((java.math.BigDecimal)field_COLN_INT_WC.getValue())));//$JR_EXPR_ID=10$
                break;
            }
            case 11 : 
            {
                value = (java.math.BigDecimal)(new java.math.BigDecimal("0"));//$JR_EXPR_ID=11$
                break;
            }
            case 12 : 
            {
                value = (java.math.BigDecimal)(((((java.math.BigDecimal)field_OB_YESTER_YR_WC.getValue())).add(((java.math.BigDecimal)field_ob_cur_yr_wc.getValue()) ).subtract(((java.math.BigDecimal)field_coln_cur_yr_wc.getValue())).add(((java.math.BigDecimal)field_COLN_YESTER_YR_WC.getValue()))));//$JR_EXPR_ID=12$
                break;
            }
            case 13 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_INT_RATE.getValue()));//$JR_EXPR_ID=13$
                break;
            }
            case 14 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_Balance_after_other_charge.getEstimatedValue()).add(((java.math.BigDecimal)variable_BALANCE_MC.getEstimatedValue())).add(((java.math.BigDecimal)field_OB_INT_AMT_WC.getValue())));//$JR_EXPR_ID=14$
                break;
            }
            case 15 : 
            {
                value = (java.math.BigDecimal)(new java.math.BigDecimal("0"));//$JR_EXPR_ID=15$
                break;
            }
            case 16 : 
            {
                value = (java.math.BigDecimal)((((java.math.BigDecimal)field_OB_MAINT_CHARGES.getValue())).subtract(((java.math.BigDecimal)field_coln_maint.getValue())));//$JR_EXPR_ID=16$
                break;
            }
            case 17 : 
            {
                value = (java.math.BigDecimal)(new java.math.BigDecimal("0"));//$JR_EXPR_ID=17$
                break;
            }
            case 18 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_BALANCE.getEstimatedValue()).add(((java.math.BigDecimal)field_MONTH_BILL_AMT.getValue())));//$JR_EXPR_ID=18$
                break;
            }
            case 19 : 
            {
                value = (java.math.BigDecimal)((((java.math.BigDecimal)field_OB_YESTER_YR_WC.getValue())).add(((java.math.BigDecimal)field_ob_cur_yr_wc.getValue())));//$JR_EXPR_ID=19$
                break;
            }
            case 20 : 
            {
                value = (java.math.BigDecimal)(new java.math.BigDecimal("0"));//$JR_EXPR_ID=20$
                break;
            }
            case 21 : 
            {
                value = (java.math.BigDecimal)((((java.math.BigDecimal)field_ob_cur_yr_wc.getValue())).add(((java.math.BigDecimal)field_OB_YESTER_YR_WC.getValue())).add(((java.math.BigDecimal)field_OB_MAINT_CHARGES.getValue())).add(((java.math.BigDecimal)field_OB_INT_AMT_WC.getValue())));//$JR_EXPR_ID=21$
                break;
            }
            case 22 : 
            {
                value = (java.math.BigDecimal)(new java.math.BigDecimal("0"));//$JR_EXPR_ID=22$
                break;
            }
            case 23 : 
            {
                value = (java.math.BigDecimal)((((java.math.BigDecimal)field_coln_cur_yr_wc.getValue())).add(((java.math.BigDecimal)field_coln_maint.getValue())).add (((java.math.BigDecimal)field_COLN_YESTER_YR_WC.getValue())).add(((java.math.BigDecimal)field_COLN_INT_WC.getValue())));//$JR_EXPR_ID=23$
                break;
            }
            case 24 : 
            {
                value = (java.math.BigDecimal)(new java.math.BigDecimal("0"));//$JR_EXPR_ID=24$
                break;
            }
            case 25 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_sum1.getEstimatedValue()));//$JR_EXPR_ID=25$
                break;
            }
            case 26 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_BALANCE.getEstimatedValue()).add(((java.math.BigDecimal)variable_net_bal.getEstimatedValue())));//$JR_EXPR_ID=26$
                break;
            }
            case 27 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_BALANCE_WC.getEstimatedValue()).multiply( ((java.math.BigDecimal)variable_mon_int.getEstimatedValue()) ).divide(new java.math.BigDecimal("100") ));//$JR_EXPR_ID=27$
                break;
            }
            case 28 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_bal_1.getEstimatedValue()).add( ((java.math.BigDecimal)field_MONTH_BILL_AMT.getValue()) ).add(((java.math.BigDecimal)field_DMD_FOR_MTH_MC.getValue())));//$JR_EXPR_ID=28$
                break;
            }
            case 29 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_MONTH_BILL_AMT.getValue()).add( ((java.math.BigDecimal)variable_bal_1.getEstimatedValue())).add(((java.math.BigDecimal)field_DMD_FOR_MTH_MC.getValue())));//$JR_EXPR_ID=29$
                break;
            }
            case 30 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_BALANCE.getEstimatedValue()).add(((java.math.BigDecimal)variable_net_bal.getEstimatedValue())));//$JR_EXPR_ID=30$
                break;
            }
            case 31 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_MONTH_BILL_AMT.getValue()).add ( ((java.math.BigDecimal)field_DMD_FOR_MTH_MC.getValue()) ).add(((java.math.BigDecimal)field_INT_CALC_WC.getValue())));//$JR_EXPR_ID=31$
                break;
            }
            case 32 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_Balance_after_other_charge.getEstimatedValue()));//$JR_EXPR_ID=32$
                break;
            }
            case 33 : 
            {
                value = (java.math.BigDecimal)((((java.math.BigDecimal)field_DMD_FOR_MTH_MC.getValue())).add(((java.math.BigDecimal)variable_BALANCE_MC.getEstimatedValue())));//$JR_EXPR_ID=33$
                break;
            }
            case 34 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_BAL_INT.getEstimatedValue()));//$JR_EXPR_ID=34$
                break;
            }
            case 35 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_BALANCE_WC.getEstimatedValue()));//$JR_EXPR_ID=35$
                break;
            }
            case 36 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_Balance_after_other_charge.getEstimatedValue()).add(  ((java.math.BigDecimal)field_MONTH_BILL_AMT.getValue()) ));//$JR_EXPR_ID=36$
                break;
            }
            case 37 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_Balance_after_other_charge.getEstimatedValue()).add(((java.math.BigDecimal)variable_BALANCE_MC.getEstimatedValue())).add(  ( ((java.math.BigDecimal)variable_BAL_INT.getEstimatedValue()))));//$JR_EXPR_ID=37$
                break;
            }
            case 38 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_Balance_new.getEstimatedValue()).add(  ((java.math.BigDecimal)variable_row1_sum.getEstimatedValue())));//$JR_EXPR_ID=38$
                break;
            }
            case 39 : 
            {
                value = (java.math.BigDecimal)((((java.math.BigDecimal)field_ADD_CHARGES_WC.getValue())).subtract( ((java.math.BigDecimal)field_MINUS_CHARGES_WC.getValue())));//$JR_EXPR_ID=39$
                break;
            }
            case 40 : 
            {
                value = (java.math.BigDecimal)((((java.math.BigDecimal)field_ADD_CHARGES_MAINT.getValue())).subtract( ((java.math.BigDecimal)field_MINUS_CHARGES_MAINT.getValue())));//$JR_EXPR_ID=40$
                break;
            }
            case 41 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_INT_CALC_WC.getValue()).multiply(new java.math.BigDecimal("100")).divide( ((java.math.BigDecimal)field_INT_RATE.getValue())));//$JR_EXPR_ID=41$
                break;
            }
            case 42 : 
            {
                value = (java.lang.String)("<<Penalty @"+((java.math.BigDecimal)field_INT_RATE.getValue())+"% for Rs.");//$JR_EXPR_ID=42$
                break;
            }
            case 43 : 
            {
                value = (java.lang.String)(">>"+((java.math.BigDecimal)field_INT_CALC_WC.getValue()));//$JR_EXPR_ID=43$
                break;
            }
            case 44 : 
            {
                value = (java.math.BigDecimal)((((java.math.BigDecimal)field_ADD_CHARGES_INT.getValue())).subtract( ((java.math.BigDecimal)field_MINUS_CHARGES_INT.getValue())));//$JR_EXPR_ID=44$
                break;
            }
            case 45 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_netotheramt.getEstimatedValue()).add(((java.math.BigDecimal)variable_netotheramt_int.getEstimatedValue())));//$JR_EXPR_ID=45$
                break;
            }
            case 46 : 
            {
                value = (java.lang.String)("Bill of cost water supplied during the month ending " + ((java.lang.String)field_BILL_MONTH.getValue()) + " / " + ((java.math.BigDecimal)field_BILL_YEAR.getValue()));//$JR_EXPR_ID=46$
                break;
            }
            case 47 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_imgpath.getValue())+"twademblem.gif");//$JR_EXPR_ID=47$
                break;
            }
            case 48 : 
            {
                value = (java.lang.String)(((java.lang.String)field_BILLING_ADDRESS1.getValue()));//$JR_EXPR_ID=48$
                break;
            }
            case 49 : 
            {
                value = (java.lang.String)(((java.lang.String)field_BILLING_ADDRESS2.getValue()));//$JR_EXPR_ID=49$
                break;
            }
            case 50 : 
            {
                value = (java.lang.String)(((java.lang.String)field_BILLING_ADDRESS3.getValue()));//$JR_EXPR_ID=50$
                break;
            }
            case 51 : 
            {
                value = (java.lang.String)(((java.lang.String)field_BILLING_PIN_CODE.getValue()));//$JR_EXPR_ID=51$
                break;
            }
            case 52 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_MONTH_BILL_AMT.getValue()));//$JR_EXPR_ID=52$
                break;
            }
            case 53 : 
            {
                value = (java.lang.String)("The amount should be sent by Local Bank Cheque (Subject to Realisation) or DD in favour of Executive Engineer, TWAD    Board, " + ((java.lang.String)field_OFFICE_NAME.getValue()));//$JR_EXPR_ID=53$
                break;
            }
            case 54 : 
            {
                value = (java.lang.String)(((java.lang.String)field_OFFICE_NAME.getValue()));//$JR_EXPR_ID=54$
                break;
            }
            case 55 : 
            {
                value = (java.lang.String)(((java.lang.String)field_AMT_WORDS.getValue())+" Only");//$JR_EXPR_ID=55$
                break;
            }
            case 56 : 
            {
                value = (java.lang.Object)(((java.math.BigDecimal)field_BENEFICIARY_SNO.getValue()));//$JR_EXPR_ID=56$
                break;
            }
            case 57 : 
            {
                value = (java.sql.Connection)(((java.sql.Connection)parameter_REPORT_CONNECTION.getValue()));//$JR_EXPR_ID=57$
                break;
            }
            case 58 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_ctxpath.getValue()) + "/offices.jasper");//$JR_EXPR_ID=58$
                break;
            }
            case 59 : 
            {
                value = (java.lang.Object)(((java.lang.String)field_BILL_MONTH.getValue()));//$JR_EXPR_ID=59$
                break;
            }
            case 60 : 
            {
                value = (java.lang.Object)(((java.math.BigDecimal)field_BILL_YEAR.getValue()));//$JR_EXPR_ID=60$
                break;
            }
            case 61 : 
            {
                value = (java.lang.Object)(((java.math.BigDecimal)field_BILL_SNO.getValue()));//$JR_EXPR_ID=61$
                break;
            }
            case 62 : 
            {
                value = (java.sql.Connection)(((java.sql.Connection)parameter_REPORT_CONNECTION.getValue()));//$JR_EXPR_ID=62$
                break;
            }
            case 63 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_ctxpath.getValue()) + "all_Bill_Demand_2.jasper");//$JR_EXPR_ID=63$
                break;
            }
            case 64 : 
            {
                value = (java.lang.Object)(((java.lang.String)field_BILL_MONTH.getValue()));//$JR_EXPR_ID=64$
                break;
            }
            case 65 : 
            {
                value = (java.lang.Object)(((java.math.BigDecimal)field_BILL_YEAR.getValue()));//$JR_EXPR_ID=65$
                break;
            }
            case 66 : 
            {
                value = (java.lang.Object)(((java.lang.String)parameter_ctxpath.getValue()));//$JR_EXPR_ID=66$
                break;
            }
            case 67 : 
            {
                value = (java.lang.Object)(((java.math.BigDecimal)field_BILL_SNO.getValue()));//$JR_EXPR_ID=67$
                break;
            }
            case 68 : 
            {
                value = (java.sql.Connection)(((java.sql.Connection)parameter_REPORT_CONNECTION.getValue()));//$JR_EXPR_ID=68$
                break;
            }
            case 69 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_ctxpath.getValue()) + "all_bill_demand_subreport0.jasper");//$JR_EXPR_ID=69$
                break;
            }
            case 70 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_BAL_INT.getEstimatedValue()));//$JR_EXPR_ID=70$
                break;
            }
            case 71 : 
            {
                value = (java.math.BigDecimal)((((java.math.BigDecimal)field_coln_maint.getValue())));//$JR_EXPR_ID=71$
                break;
            }
            case 72 : 
            {
                value = (java.math.BigDecimal)((((java.math.BigDecimal)field_coln_cur_yr_wc.getValue())).add(((java.math.BigDecimal)field_COLN_YESTER_YR_WC.getValue())));//$JR_EXPR_ID=72$
                break;
            }
            case 73 : 
            {
                value = (java.math.BigDecimal)((((java.math.BigDecimal)field_OB_MAINT_CHARGES.getValue())));//$JR_EXPR_ID=73$
                break;
            }
            case 74 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_MONTH_BILL_AMT.getValue()));//$JR_EXPR_ID=74$
                break;
            }
            case 75 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_Balance_after_other_charge.getEstimatedValue()));//$JR_EXPR_ID=75$
                break;
            }
            case 76 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_BALANCE_MC.getEstimatedValue()));//$JR_EXPR_ID=76$
                break;
            }
            case 77 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_TOT_OB.getEstimatedValue()));//$JR_EXPR_ID=77$
                break;
            }
            case 78 : 
            {
                value = (java.math.BigDecimal)((((java.math.BigDecimal)field_OB_INT_AMT_WC.getValue())));//$JR_EXPR_ID=78$
                break;
            }
            case 79 : 
            {
                value = (java.math.BigDecimal)((((java.math.BigDecimal)field_COLN_INT_WC.getValue())));//$JR_EXPR_ID=79$
                break;
            }
            case 80 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_INT_CALC_WC.getValue()));//$JR_EXPR_ID=80$
                break;
            }
            case 81 : 
            {
                value = (java.math.BigDecimal)((((java.math.BigDecimal)field_DMD_FOR_MTH_MC.getValue())));//$JR_EXPR_ID=81$
                break;
            }
            case 82 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_net_sum_new.getEstimatedValue()).add(((java.math.BigDecimal)variable_netotheramt.getEstimatedValue())));//$JR_EXPR_ID=82$
                break;
            }
            case 83 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_net_sum3.getEstimatedValue()).add(((java.math.BigDecimal)variable_netotheramt_mc.getEstimatedValue())));//$JR_EXPR_ID=83$
                break;
            }
            case 84 : 
            {
                value = (java.math.BigDecimal)((((java.math.BigDecimal)variable_BAL_INT.getEstimatedValue()).add(((java.math.BigDecimal)field_INT_CALC_WC.getValue()))).add(((java.math.BigDecimal)variable_netotheramt_int.getEstimatedValue())));//$JR_EXPR_ID=84$
                break;
            }
            case 85 : 
            {
                value = (java.lang.String)(((java.lang.String)field_OFFICE_NAME.getValue()));//$JR_EXPR_ID=85$
                break;
            }
            case 86 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_Balance_new.getEstimatedValue()));//$JR_EXPR_ID=86$
                break;
            }
            case 87 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_OB.getEstimatedValue()));//$JR_EXPR_ID=87$
                break;
            }
            case 88 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_COLN.getEstimatedValue()));//$JR_EXPR_ID=88$
                break;
            }
            case 89 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_row1_sum.getEstimatedValue()));//$JR_EXPR_ID=89$
                break;
            }
            case 90 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_net_sum_1_new.getEstimatedValue()) .add(((java.math.BigDecimal)variable_netotheramt.getEstimatedValue())).add(((java.math.BigDecimal)variable_netotheramt_mc.getEstimatedValue())).add(((java.math.BigDecimal)variable_netotheramt_int.getEstimatedValue())));//$JR_EXPR_ID=90$
                break;
            }
            case 91 : 
            {
                value = (java.lang.String)(" Note :" + ((java.lang.String)field_REMARKS.getValue()));//$JR_EXPR_ID=91$
                break;
            }
            case 92 : 
            {
                value = (java.lang.String)(" Add : " + ((java.math.BigDecimal)field_ADD_CHARGES_WC.getValue()));//$JR_EXPR_ID=92$
                break;
            }
            case 93 : 
            {
                value = (java.lang.String)("Subtract:  "+ ((java.math.BigDecimal)field_MINUS_CHARGES_WC.getValue()));//$JR_EXPR_ID=93$
                break;
            }
            case 94 : 
            {
                value = (java.lang.String)(""+((java.lang.String)field_BILL_MONTH.getValue())+((java.math.BigDecimal)field_BILL_YEAR.getValue())+((java.lang.String)field_DIV_BILL_NO.getValue()));//$JR_EXPR_ID=94$
                break;
            }
            case 95 : 
            {
                value = (java.lang.String)(((java.lang.String)field_BILLING_DT.getValue()));//$JR_EXPR_ID=95$
                break;
            }
            case 96 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_netotheramt.getEstimatedValue()));//$JR_EXPR_ID=96$
                break;
            }
            case 97 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_net_tota_other_charges.getEstimatedValue()));//$JR_EXPR_ID=97$
                break;
            }
            case 98 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_netotheramt_mc.getEstimatedValue()));//$JR_EXPR_ID=98$
                break;
            }
            case 99 : 
            {
                value = (java.lang.String)(((java.lang.String)field_BENEFICIARY_NAME.getValue()));//$JR_EXPR_ID=99$
                break;
            }
           default :
           {
               value = evaluateEstimated1(id);
           }
        }
        
        return value;
    }


    /**
     *
     */
    private Object evaluateEstimated1(int id) throws Throwable
    {
        Object value = null;

        switch (id)
        {
            case 100 : 
            {
                value = (java.lang.String)(((java.lang.String)variable_int_display.getEstimatedValue()));//$JR_EXPR_ID=100$
                break;
            }
            case 101 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_int_amt.getEstimatedValue()));//$JR_EXPR_ID=101$
                break;
            }
            case 102 : 
            {
                value = (java.lang.String)(((java.lang.String)variable_int_display_2.getEstimatedValue()));//$JR_EXPR_ID=102$
                break;
            }
            case 103 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_netotheramt_int.getEstimatedValue()));//$JR_EXPR_ID=103$
                break;
            }
           default :
           {
           }
        }
        
        return value;
    }


}
