/*
 * Generated by JasperReports - 13/7/23 12:47 PM
 */
import net.sf.jasperreports.engine.*;
import net.sf.jasperreports.engine.fill.*;

import java.util.*;
import java.math.*;
import java.text.*;
import java.io.*;
import java.net.*;

import net.sf.jasperreports.engine.*;
import java.util.*;
import net.sf.jasperreports.engine.data.*;


/**
 *
 */
public class count_report_new1_1689232653241_637381 extends JREvaluator
{


    /**
     *
     */
    private JRFillParameter parameter_IS_IGNORE_PAGINATION = null;
    private JRFillParameter parameter_REPORT_CONNECTION = null;
    private JRFillParameter parameter_year = null;
    private JRFillParameter parameter_REPORT_LOCALE = null;
    private JRFillParameter parameter_REPORT_TIME_ZONE = null;
    private JRFillParameter parameter_REPORT_TEMPLATES = null;
    private JRFillParameter parameter_REPORT_MAX_COUNT = null;
    private JRFillParameter parameter_REPORT_SCRIPTLET = null;
    private JRFillParameter parameter_REPORT_FILE_RESOLVER = null;
    private JRFillParameter parameter_month = null;
    private JRFillParameter parameter_REPORT_FORMAT_FACTORY = null;
    private JRFillParameter parameter_REPORT_PARAMETERS_MAP = null;
    private JRFillParameter parameter_REPORT_RESOURCE_BUNDLE = null;
    private JRFillParameter parameter_REPORT_DATA_SOURCE = null;
    private JRFillParameter parameter_REPORT_CLASS_LOADER = null;
    private JRFillParameter parameter_REPORT_URL_HANDLER_FACTORY = null;
    private JRFillParameter parameter_REPORT_VIRTUALIZER = null;
    private JRFillParameter parameter_monthval = null;
    private JRFillField field_MET2COUNT = null;
    private JRFillField field_PRC = null;
    private JRFillField field_METFRCOUNT = null;
    private JRFillField field_PRVC = null;
    private JRFillField field_BEN2COUNT = null;
    private JRFillField field_DCB_FREEZE = null;
    private JRFillField field_METNFRCOUNT = null;
    private JRFillField field_tb_status = null;
    private JRFillField field_PRCR = null;
    private JRFillField field_prvcount = null;
    private JRFillField field_QTY = null;
    private JRFillField field_METSETDONER = null;
    private JRFillField field_PRFC = null;
    private JRFillField field_MET1COUNT = null;
    private JRFillField field_METNOTSETR = null;
    private JRFillField field_COL = null;
    private JRFillField field_OP = null;
    private JRFillField field_ST = null;
    private JRFillField field_LTCOUNT = null;
    private JRFillField field_BEN1COUNT = null;
    private JRFillField field_AMT = null;
    private JRFillField field_DMDC = null;
    private JRFillField field_RATENOTCOUNT = null;
    private JRFillField field_DIV = null;
    private JRFillField field_REG = null;
    private JRFillField field_RATECOUNT = null;
    private JRFillField field_OFFICE_ID = null;
    private JRFillVariable variable_PAGE_NUMBER = null;
    private JRFillVariable variable_COLUMN_NUMBER = null;
    private JRFillVariable variable_REPORT_COUNT = null;
    private JRFillVariable variable_PAGE_COUNT = null;
    private JRFillVariable variable_COLUMN_COUNT = null;
    private JRFillVariable variable_REG_COUNT = null;
    private JRFillVariable variable_DIV_COUNT = null;
    private JRFillVariable variable_total = null;
    private JRFillVariable variable_dt = null;
    private JRFillVariable variable_tot_private = null;
    private JRFillVariable variable_tot_local = null;
    private JRFillVariable variable_total_ben = null;
    private JRFillVariable variable_total_pr = null;
    private JRFillVariable variable_total_demand = null;
    private JRFillVariable variable_total_collection = null;
    private JRFillVariable variable_tot_private_ben = null;
    private JRFillVariable variable_total_demand_ben = null;
    private JRFillVariable variable_total_ledger_ben = null;


    /**
     *
     */
    public void customizedInit(
        Map pm,
        Map fm,
        Map vm
        )
    {
        initParams(pm);
        initFields(fm);
        initVars(vm);
    }


    /**
     *
     */
    private void initParams(Map pm)
    {
        parameter_IS_IGNORE_PAGINATION = (JRFillParameter)pm.get("IS_IGNORE_PAGINATION");
        parameter_REPORT_CONNECTION = (JRFillParameter)pm.get("REPORT_CONNECTION");
        parameter_year = (JRFillParameter)pm.get("year");
        parameter_REPORT_LOCALE = (JRFillParameter)pm.get("REPORT_LOCALE");
        parameter_REPORT_TIME_ZONE = (JRFillParameter)pm.get("REPORT_TIME_ZONE");
        parameter_REPORT_TEMPLATES = (JRFillParameter)pm.get("REPORT_TEMPLATES");
        parameter_REPORT_MAX_COUNT = (JRFillParameter)pm.get("REPORT_MAX_COUNT");
        parameter_REPORT_SCRIPTLET = (JRFillParameter)pm.get("REPORT_SCRIPTLET");
        parameter_REPORT_FILE_RESOLVER = (JRFillParameter)pm.get("REPORT_FILE_RESOLVER");
        parameter_month = (JRFillParameter)pm.get("month");
        parameter_REPORT_FORMAT_FACTORY = (JRFillParameter)pm.get("REPORT_FORMAT_FACTORY");
        parameter_REPORT_PARAMETERS_MAP = (JRFillParameter)pm.get("REPORT_PARAMETERS_MAP");
        parameter_REPORT_RESOURCE_BUNDLE = (JRFillParameter)pm.get("REPORT_RESOURCE_BUNDLE");
        parameter_REPORT_DATA_SOURCE = (JRFillParameter)pm.get("REPORT_DATA_SOURCE");
        parameter_REPORT_CLASS_LOADER = (JRFillParameter)pm.get("REPORT_CLASS_LOADER");
        parameter_REPORT_URL_HANDLER_FACTORY = (JRFillParameter)pm.get("REPORT_URL_HANDLER_FACTORY");
        parameter_REPORT_VIRTUALIZER = (JRFillParameter)pm.get("REPORT_VIRTUALIZER");
        parameter_monthval = (JRFillParameter)pm.get("monthval");
    }


    /**
     *
     */
    private void initFields(Map fm)
    {
        field_MET2COUNT = (JRFillField)fm.get("MET2COUNT");
        field_PRC = (JRFillField)fm.get("PRC");
        field_METFRCOUNT = (JRFillField)fm.get("METFRCOUNT");
        field_PRVC = (JRFillField)fm.get("PRVC");
        field_BEN2COUNT = (JRFillField)fm.get("BEN2COUNT");
        field_DCB_FREEZE = (JRFillField)fm.get("DCB_FREEZE");
        field_METNFRCOUNT = (JRFillField)fm.get("METNFRCOUNT");
        field_tb_status = (JRFillField)fm.get("tb_status");
        field_PRCR = (JRFillField)fm.get("PRCR");
        field_prvcount = (JRFillField)fm.get("prvcount");
        field_QTY = (JRFillField)fm.get("QTY");
        field_METSETDONER = (JRFillField)fm.get("METSETDONER");
        field_PRFC = (JRFillField)fm.get("PRFC");
        field_MET1COUNT = (JRFillField)fm.get("MET1COUNT");
        field_METNOTSETR = (JRFillField)fm.get("METNOTSETR");
        field_COL = (JRFillField)fm.get("COL");
        field_OP = (JRFillField)fm.get("OP");
        field_ST = (JRFillField)fm.get("ST");
        field_LTCOUNT = (JRFillField)fm.get("LTCOUNT");
        field_BEN1COUNT = (JRFillField)fm.get("BEN1COUNT");
        field_AMT = (JRFillField)fm.get("AMT");
        field_DMDC = (JRFillField)fm.get("DMDC");
        field_RATENOTCOUNT = (JRFillField)fm.get("RATENOTCOUNT");
        field_DIV = (JRFillField)fm.get("DIV");
        field_REG = (JRFillField)fm.get("REG");
        field_RATECOUNT = (JRFillField)fm.get("RATECOUNT");
        field_OFFICE_ID = (JRFillField)fm.get("OFFICE_ID");
    }


    /**
     *
     */
    private void initVars(Map vm)
    {
        variable_PAGE_NUMBER = (JRFillVariable)vm.get("PAGE_NUMBER");
        variable_COLUMN_NUMBER = (JRFillVariable)vm.get("COLUMN_NUMBER");
        variable_REPORT_COUNT = (JRFillVariable)vm.get("REPORT_COUNT");
        variable_PAGE_COUNT = (JRFillVariable)vm.get("PAGE_COUNT");
        variable_COLUMN_COUNT = (JRFillVariable)vm.get("COLUMN_COUNT");
        variable_REG_COUNT = (JRFillVariable)vm.get("REG_COUNT");
        variable_DIV_COUNT = (JRFillVariable)vm.get("DIV_COUNT");
        variable_total = (JRFillVariable)vm.get("total");
        variable_dt = (JRFillVariable)vm.get("dt");
        variable_tot_private = (JRFillVariable)vm.get("tot_private");
        variable_tot_local = (JRFillVariable)vm.get("tot_local");
        variable_total_ben = (JRFillVariable)vm.get("total_ben");
        variable_total_pr = (JRFillVariable)vm.get("total_pr");
        variable_total_demand = (JRFillVariable)vm.get("total_demand");
        variable_total_collection = (JRFillVariable)vm.get("total_collection");
        variable_tot_private_ben = (JRFillVariable)vm.get("tot_private_ben");
        variable_total_demand_ben = (JRFillVariable)vm.get("total_demand_ben");
        variable_total_ledger_ben = (JRFillVariable)vm.get("total_ledger_ben");
    }


    /**
     *
     */
    public Object evaluate(int id) throws Throwable
    {
        Object value = null;

        switch (id)
        {
            case 0 : 
            {
                value = (java.lang.Integer)(new Integer(1));//$JR_EXPR_ID=0$
                break;
            }
            case 1 : 
            {
                value = (java.lang.Integer)(new Integer(1));//$JR_EXPR_ID=1$
                break;
            }
            case 2 : 
            {
                value = (java.lang.Integer)(new Integer(1));//$JR_EXPR_ID=2$
                break;
            }
            case 3 : 
            {
                value = (java.lang.Integer)(new Integer(0));//$JR_EXPR_ID=3$
                break;
            }
            case 4 : 
            {
                value = (java.lang.Integer)(new Integer(1));//$JR_EXPR_ID=4$
                break;
            }
            case 5 : 
            {
                value = (java.lang.Integer)(new Integer(0));//$JR_EXPR_ID=5$
                break;
            }
            case 6 : 
            {
                value = (java.lang.Integer)(new Integer(1));//$JR_EXPR_ID=6$
                break;
            }
            case 7 : 
            {
                value = (java.lang.Integer)(new Integer(0));//$JR_EXPR_ID=7$
                break;
            }
            case 8 : 
            {
                value = (java.lang.Integer)(new Integer(1));//$JR_EXPR_ID=8$
                break;
            }
            case 9 : 
            {
                value = (java.lang.Integer)(new Integer(0));//$JR_EXPR_ID=9$
                break;
            }
            case 10 : 
            {
                value = (java.lang.Integer)(new Integer(1));//$JR_EXPR_ID=10$
                break;
            }
            case 11 : 
            {
                value = (java.lang.Integer)(new Integer(0));//$JR_EXPR_ID=11$
                break;
            }
            case 12 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_BEN1COUNT.getValue()).add(((java.math.BigDecimal)field_BEN2COUNT.getValue())));//$JR_EXPR_ID=12$
                break;
            }
            case 13 : 
            {
                value = (java.util.Date)(new Date());//$JR_EXPR_ID=13$
                break;
            }
            case 14 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_prvcount.getValue()));//$JR_EXPR_ID=14$
                break;
            }
            case 15 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_BEN1COUNT.getValue()));//$JR_EXPR_ID=15$
                break;
            }
            case 16 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_total.getValue()));//$JR_EXPR_ID=16$
                break;
            }
            case 17 : 
            {
                value = (java.math.BigDecimal)((((java.math.BigDecimal)field_QTY.getValue())));//$JR_EXPR_ID=17$
                break;
            }
            case 18 : 
            {
                value = (java.math.BigDecimal)(new BigDecimal(((java.math.BigDecimal)field_AMT.getValue())));//$JR_EXPR_ID=18$
                break;
            }
            case 19 : 
            {
                value = (java.math.BigDecimal)(new BigDecimal(((java.math.BigDecimal)field_COL.getValue())));//$JR_EXPR_ID=19$
                break;
            }
            case 20 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_BEN2COUNT.getValue()));//$JR_EXPR_ID=20$
                break;
            }
            case 21 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_DMDC.getValue()));//$JR_EXPR_ID=21$
                break;
            }
            case 22 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_LTCOUNT.getValue()));//$JR_EXPR_ID=22$
                break;
            }
            case 23 : 
            {
                value = (java.lang.Object)(((java.lang.String)field_REG.getValue()));//$JR_EXPR_ID=23$
                break;
            }
            case 24 : 
            {
                value = (java.lang.String)(((java.lang.String)field_REG.getValue()));//$JR_EXPR_ID=24$
                break;
            }
            case 25 : 
            {
                value = (java.lang.Object)(((java.lang.String)field_DIV.getValue()));//$JR_EXPR_ID=25$
                break;
            }
            case 26 : 
            {
                value = (java.util.Date)(new Date());//$JR_EXPR_ID=26$
                break;
            }
            case 27 : 
            {
                value = (java.lang.String)("  Statistical Report  -  TWAD Head Office  " + ((java.lang.String)parameter_monthval.getValue())+"  "+((java.lang.String)parameter_year.getValue()));//$JR_EXPR_ID=27$
                break;
            }
            case 28 : 
            {
                value = (java.lang.String)(((java.lang.String)field_DIV.getValue()));//$JR_EXPR_ID=28$
                break;
            }
            case 29 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_prvcount.getValue()));//$JR_EXPR_ID=29$
                break;
            }
            case 30 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_BEN1COUNT.getValue()));//$JR_EXPR_ID=30$
                break;
            }
            case 31 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_BEN2COUNT.getValue()));//$JR_EXPR_ID=31$
                break;
            }
            case 32 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_MET1COUNT.getValue()).add( ((java.math.BigDecimal)field_MET2COUNT.getValue())));//$JR_EXPR_ID=32$
                break;
            }
            case 33 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_METFRCOUNT.getValue()));//$JR_EXPR_ID=33$
                break;
            }
            case 34 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_RATECOUNT.getValue()));//$JR_EXPR_ID=34$
                break;
            }
            case 35 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_total.getValue()));//$JR_EXPR_ID=35$
                break;
            }
            case 36 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_OP.getValue()));//$JR_EXPR_ID=36$
                break;
            }
            case 37 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_PRC.getValue()));//$JR_EXPR_ID=37$
                break;
            }
            case 38 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_PRCR.getValue()));//$JR_EXPR_ID=38$
                break;
            }
            case 39 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_PRVC.getValue()));//$JR_EXPR_ID=39$
                break;
            }
            case 40 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_PRFC.getValue()));//$JR_EXPR_ID=40$
                break;
            }
            case 41 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_DMDC.getValue()));//$JR_EXPR_ID=41$
                break;
            }
            case 42 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_METSETDONER.getValue()));//$JR_EXPR_ID=42$
                break;
            }
            case 43 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_ST.getValue()));//$JR_EXPR_ID=43$
                break;
            }
            case 44 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_LTCOUNT.getValue()));//$JR_EXPR_ID=44$
                break;
            }
            case 45 : 
            {
                value = (java.lang.String)(((java.lang.String)field_tb_status.getValue()));//$JR_EXPR_ID=45$
                break;
            }
            case 46 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_AMT.getValue()));//$JR_EXPR_ID=46$
                break;
            }
            case 47 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_QTY.getValue()));//$JR_EXPR_ID=47$
                break;
            }
            case 48 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_COL.getValue()));//$JR_EXPR_ID=48$
                break;
            }
            case 49 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_OFFICE_ID.getValue()));//$JR_EXPR_ID=49$
                break;
            }
            case 50 : 
            {
                value = (java.lang.Integer)(((java.lang.Integer)variable_REG_COUNT.getValue()));//$JR_EXPR_ID=50$
                break;
            }
            case 51 : 
            {
                value = (java.lang.String)(((java.lang.String)field_DCB_FREEZE.getValue()));//$JR_EXPR_ID=51$
                break;
            }
            case 52 : 
            {
                value = (java.util.Date)(new java.util.Date());//$JR_EXPR_ID=52$
                break;
            }
            case 53 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_tot_private.getValue()));//$JR_EXPR_ID=53$
                break;
            }
            case 54 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_tot_local.getValue()));//$JR_EXPR_ID=54$
                break;
            }
            case 55 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_tot_private_ben.getValue()));//$JR_EXPR_ID=55$
                break;
            }
            case 56 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_total_ben.getValue()));//$JR_EXPR_ID=56$
                break;
            }
            case 57 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_total_pr.getValue()));//$JR_EXPR_ID=57$
                break;
            }
            case 58 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_total_demand.getValue()));//$JR_EXPR_ID=58$
                break;
            }
            case 59 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_total_collection.getValue()));//$JR_EXPR_ID=59$
                break;
            }
            case 60 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_total_demand_ben.getValue()));//$JR_EXPR_ID=60$
                break;
            }
            case 61 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_total_ledger_ben.getValue()));//$JR_EXPR_ID=61$
                break;
            }
           default :
           {
           }
        }
        
        return value;
    }


    /**
     *
     */
    public Object evaluateOld(int id) throws Throwable
    {
        Object value = null;

        switch (id)
        {
            case 0 : 
            {
                value = (java.lang.Integer)(new Integer(1));//$JR_EXPR_ID=0$
                break;
            }
            case 1 : 
            {
                value = (java.lang.Integer)(new Integer(1));//$JR_EXPR_ID=1$
                break;
            }
            case 2 : 
            {
                value = (java.lang.Integer)(new Integer(1));//$JR_EXPR_ID=2$
                break;
            }
            case 3 : 
            {
                value = (java.lang.Integer)(new Integer(0));//$JR_EXPR_ID=3$
                break;
            }
            case 4 : 
            {
                value = (java.lang.Integer)(new Integer(1));//$JR_EXPR_ID=4$
                break;
            }
            case 5 : 
            {
                value = (java.lang.Integer)(new Integer(0));//$JR_EXPR_ID=5$
                break;
            }
            case 6 : 
            {
                value = (java.lang.Integer)(new Integer(1));//$JR_EXPR_ID=6$
                break;
            }
            case 7 : 
            {
                value = (java.lang.Integer)(new Integer(0));//$JR_EXPR_ID=7$
                break;
            }
            case 8 : 
            {
                value = (java.lang.Integer)(new Integer(1));//$JR_EXPR_ID=8$
                break;
            }
            case 9 : 
            {
                value = (java.lang.Integer)(new Integer(0));//$JR_EXPR_ID=9$
                break;
            }
            case 10 : 
            {
                value = (java.lang.Integer)(new Integer(1));//$JR_EXPR_ID=10$
                break;
            }
            case 11 : 
            {
                value = (java.lang.Integer)(new Integer(0));//$JR_EXPR_ID=11$
                break;
            }
            case 12 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_BEN1COUNT.getOldValue()).add(((java.math.BigDecimal)field_BEN2COUNT.getOldValue())));//$JR_EXPR_ID=12$
                break;
            }
            case 13 : 
            {
                value = (java.util.Date)(new Date());//$JR_EXPR_ID=13$
                break;
            }
            case 14 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_prvcount.getOldValue()));//$JR_EXPR_ID=14$
                break;
            }
            case 15 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_BEN1COUNT.getOldValue()));//$JR_EXPR_ID=15$
                break;
            }
            case 16 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_total.getOldValue()));//$JR_EXPR_ID=16$
                break;
            }
            case 17 : 
            {
                value = (java.math.BigDecimal)((((java.math.BigDecimal)field_QTY.getOldValue())));//$JR_EXPR_ID=17$
                break;
            }
            case 18 : 
            {
                value = (java.math.BigDecimal)(new BigDecimal(((java.math.BigDecimal)field_AMT.getOldValue())));//$JR_EXPR_ID=18$
                break;
            }
            case 19 : 
            {
                value = (java.math.BigDecimal)(new BigDecimal(((java.math.BigDecimal)field_COL.getOldValue())));//$JR_EXPR_ID=19$
                break;
            }
            case 20 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_BEN2COUNT.getOldValue()));//$JR_EXPR_ID=20$
                break;
            }
            case 21 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_DMDC.getOldValue()));//$JR_EXPR_ID=21$
                break;
            }
            case 22 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_LTCOUNT.getOldValue()));//$JR_EXPR_ID=22$
                break;
            }
            case 23 : 
            {
                value = (java.lang.Object)(((java.lang.String)field_REG.getOldValue()));//$JR_EXPR_ID=23$
                break;
            }
            case 24 : 
            {
                value = (java.lang.String)(((java.lang.String)field_REG.getOldValue()));//$JR_EXPR_ID=24$
                break;
            }
            case 25 : 
            {
                value = (java.lang.Object)(((java.lang.String)field_DIV.getOldValue()));//$JR_EXPR_ID=25$
                break;
            }
            case 26 : 
            {
                value = (java.util.Date)(new Date());//$JR_EXPR_ID=26$
                break;
            }
            case 27 : 
            {
                value = (java.lang.String)("  Statistical Report  -  TWAD Head Office  " + ((java.lang.String)parameter_monthval.getValue())+"  "+((java.lang.String)parameter_year.getValue()));//$JR_EXPR_ID=27$
                break;
            }
            case 28 : 
            {
                value = (java.lang.String)(((java.lang.String)field_DIV.getOldValue()));//$JR_EXPR_ID=28$
                break;
            }
            case 29 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_prvcount.getOldValue()));//$JR_EXPR_ID=29$
                break;
            }
            case 30 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_BEN1COUNT.getOldValue()));//$JR_EXPR_ID=30$
                break;
            }
            case 31 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_BEN2COUNT.getOldValue()));//$JR_EXPR_ID=31$
                break;
            }
            case 32 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_MET1COUNT.getOldValue()).add( ((java.math.BigDecimal)field_MET2COUNT.getOldValue())));//$JR_EXPR_ID=32$
                break;
            }
            case 33 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_METFRCOUNT.getOldValue()));//$JR_EXPR_ID=33$
                break;
            }
            case 34 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_RATECOUNT.getOldValue()));//$JR_EXPR_ID=34$
                break;
            }
            case 35 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_total.getOldValue()));//$JR_EXPR_ID=35$
                break;
            }
            case 36 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_OP.getOldValue()));//$JR_EXPR_ID=36$
                break;
            }
            case 37 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_PRC.getOldValue()));//$JR_EXPR_ID=37$
                break;
            }
            case 38 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_PRCR.getOldValue()));//$JR_EXPR_ID=38$
                break;
            }
            case 39 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_PRVC.getOldValue()));//$JR_EXPR_ID=39$
                break;
            }
            case 40 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_PRFC.getOldValue()));//$JR_EXPR_ID=40$
                break;
            }
            case 41 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_DMDC.getOldValue()));//$JR_EXPR_ID=41$
                break;
            }
            case 42 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_METSETDONER.getOldValue()));//$JR_EXPR_ID=42$
                break;
            }
            case 43 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_ST.getOldValue()));//$JR_EXPR_ID=43$
                break;
            }
            case 44 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_LTCOUNT.getOldValue()));//$JR_EXPR_ID=44$
                break;
            }
            case 45 : 
            {
                value = (java.lang.String)(((java.lang.String)field_tb_status.getOldValue()));//$JR_EXPR_ID=45$
                break;
            }
            case 46 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_AMT.getOldValue()));//$JR_EXPR_ID=46$
                break;
            }
            case 47 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_QTY.getOldValue()));//$JR_EXPR_ID=47$
                break;
            }
            case 48 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_COL.getOldValue()));//$JR_EXPR_ID=48$
                break;
            }
            case 49 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_OFFICE_ID.getOldValue()));//$JR_EXPR_ID=49$
                break;
            }
            case 50 : 
            {
                value = (java.lang.Integer)(((java.lang.Integer)variable_REG_COUNT.getOldValue()));//$JR_EXPR_ID=50$
                break;
            }
            case 51 : 
            {
                value = (java.lang.String)(((java.lang.String)field_DCB_FREEZE.getOldValue()));//$JR_EXPR_ID=51$
                break;
            }
            case 52 : 
            {
                value = (java.util.Date)(new java.util.Date());//$JR_EXPR_ID=52$
                break;
            }
            case 53 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_tot_private.getOldValue()));//$JR_EXPR_ID=53$
                break;
            }
            case 54 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_tot_local.getOldValue()));//$JR_EXPR_ID=54$
                break;
            }
            case 55 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_tot_private_ben.getOldValue()));//$JR_EXPR_ID=55$
                break;
            }
            case 56 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_total_ben.getOldValue()));//$JR_EXPR_ID=56$
                break;
            }
            case 57 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_total_pr.getOldValue()));//$JR_EXPR_ID=57$
                break;
            }
            case 58 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_total_demand.getOldValue()));//$JR_EXPR_ID=58$
                break;
            }
            case 59 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_total_collection.getOldValue()));//$JR_EXPR_ID=59$
                break;
            }
            case 60 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_total_demand_ben.getOldValue()));//$JR_EXPR_ID=60$
                break;
            }
            case 61 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_total_ledger_ben.getOldValue()));//$JR_EXPR_ID=61$
                break;
            }
           default :
           {
           }
        }
        
        return value;
    }


    /**
     *
     */
    public Object evaluateEstimated(int id) throws Throwable
    {
        Object value = null;

        switch (id)
        {
            case 0 : 
            {
                value = (java.lang.Integer)(new Integer(1));//$JR_EXPR_ID=0$
                break;
            }
            case 1 : 
            {
                value = (java.lang.Integer)(new Integer(1));//$JR_EXPR_ID=1$
                break;
            }
            case 2 : 
            {
                value = (java.lang.Integer)(new Integer(1));//$JR_EXPR_ID=2$
                break;
            }
            case 3 : 
            {
                value = (java.lang.Integer)(new Integer(0));//$JR_EXPR_ID=3$
                break;
            }
            case 4 : 
            {
                value = (java.lang.Integer)(new Integer(1));//$JR_EXPR_ID=4$
                break;
            }
            case 5 : 
            {
                value = (java.lang.Integer)(new Integer(0));//$JR_EXPR_ID=5$
                break;
            }
            case 6 : 
            {
                value = (java.lang.Integer)(new Integer(1));//$JR_EXPR_ID=6$
                break;
            }
            case 7 : 
            {
                value = (java.lang.Integer)(new Integer(0));//$JR_EXPR_ID=7$
                break;
            }
            case 8 : 
            {
                value = (java.lang.Integer)(new Integer(1));//$JR_EXPR_ID=8$
                break;
            }
            case 9 : 
            {
                value = (java.lang.Integer)(new Integer(0));//$JR_EXPR_ID=9$
                break;
            }
            case 10 : 
            {
                value = (java.lang.Integer)(new Integer(1));//$JR_EXPR_ID=10$
                break;
            }
            case 11 : 
            {
                value = (java.lang.Integer)(new Integer(0));//$JR_EXPR_ID=11$
                break;
            }
            case 12 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_BEN1COUNT.getValue()).add(((java.math.BigDecimal)field_BEN2COUNT.getValue())));//$JR_EXPR_ID=12$
                break;
            }
            case 13 : 
            {
                value = (java.util.Date)(new Date());//$JR_EXPR_ID=13$
                break;
            }
            case 14 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_prvcount.getValue()));//$JR_EXPR_ID=14$
                break;
            }
            case 15 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_BEN1COUNT.getValue()));//$JR_EXPR_ID=15$
                break;
            }
            case 16 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_total.getEstimatedValue()));//$JR_EXPR_ID=16$
                break;
            }
            case 17 : 
            {
                value = (java.math.BigDecimal)((((java.math.BigDecimal)field_QTY.getValue())));//$JR_EXPR_ID=17$
                break;
            }
            case 18 : 
            {
                value = (java.math.BigDecimal)(new BigDecimal(((java.math.BigDecimal)field_AMT.getValue())));//$JR_EXPR_ID=18$
                break;
            }
            case 19 : 
            {
                value = (java.math.BigDecimal)(new BigDecimal(((java.math.BigDecimal)field_COL.getValue())));//$JR_EXPR_ID=19$
                break;
            }
            case 20 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_BEN2COUNT.getValue()));//$JR_EXPR_ID=20$
                break;
            }
            case 21 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_DMDC.getValue()));//$JR_EXPR_ID=21$
                break;
            }
            case 22 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_LTCOUNT.getValue()));//$JR_EXPR_ID=22$
                break;
            }
            case 23 : 
            {
                value = (java.lang.Object)(((java.lang.String)field_REG.getValue()));//$JR_EXPR_ID=23$
                break;
            }
            case 24 : 
            {
                value = (java.lang.String)(((java.lang.String)field_REG.getValue()));//$JR_EXPR_ID=24$
                break;
            }
            case 25 : 
            {
                value = (java.lang.Object)(((java.lang.String)field_DIV.getValue()));//$JR_EXPR_ID=25$
                break;
            }
            case 26 : 
            {
                value = (java.util.Date)(new Date());//$JR_EXPR_ID=26$
                break;
            }
            case 27 : 
            {
                value = (java.lang.String)("  Statistical Report  -  TWAD Head Office  " + ((java.lang.String)parameter_monthval.getValue())+"  "+((java.lang.String)parameter_year.getValue()));//$JR_EXPR_ID=27$
                break;
            }
            case 28 : 
            {
                value = (java.lang.String)(((java.lang.String)field_DIV.getValue()));//$JR_EXPR_ID=28$
                break;
            }
            case 29 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_prvcount.getValue()));//$JR_EXPR_ID=29$
                break;
            }
            case 30 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_BEN1COUNT.getValue()));//$JR_EXPR_ID=30$
                break;
            }
            case 31 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_BEN2COUNT.getValue()));//$JR_EXPR_ID=31$
                break;
            }
            case 32 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_MET1COUNT.getValue()).add( ((java.math.BigDecimal)field_MET2COUNT.getValue())));//$JR_EXPR_ID=32$
                break;
            }
            case 33 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_METFRCOUNT.getValue()));//$JR_EXPR_ID=33$
                break;
            }
            case 34 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_RATECOUNT.getValue()));//$JR_EXPR_ID=34$
                break;
            }
            case 35 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_total.getEstimatedValue()));//$JR_EXPR_ID=35$
                break;
            }
            case 36 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_OP.getValue()));//$JR_EXPR_ID=36$
                break;
            }
            case 37 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_PRC.getValue()));//$JR_EXPR_ID=37$
                break;
            }
            case 38 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_PRCR.getValue()));//$JR_EXPR_ID=38$
                break;
            }
            case 39 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_PRVC.getValue()));//$JR_EXPR_ID=39$
                break;
            }
            case 40 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_PRFC.getValue()));//$JR_EXPR_ID=40$
                break;
            }
            case 41 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_DMDC.getValue()));//$JR_EXPR_ID=41$
                break;
            }
            case 42 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_METSETDONER.getValue()));//$JR_EXPR_ID=42$
                break;
            }
            case 43 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_ST.getValue()));//$JR_EXPR_ID=43$
                break;
            }
            case 44 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_LTCOUNT.getValue()));//$JR_EXPR_ID=44$
                break;
            }
            case 45 : 
            {
                value = (java.lang.String)(((java.lang.String)field_tb_status.getValue()));//$JR_EXPR_ID=45$
                break;
            }
            case 46 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_AMT.getValue()));//$JR_EXPR_ID=46$
                break;
            }
            case 47 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_QTY.getValue()));//$JR_EXPR_ID=47$
                break;
            }
            case 48 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_COL.getValue()));//$JR_EXPR_ID=48$
                break;
            }
            case 49 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_OFFICE_ID.getValue()));//$JR_EXPR_ID=49$
                break;
            }
            case 50 : 
            {
                value = (java.lang.Integer)(((java.lang.Integer)variable_REG_COUNT.getEstimatedValue()));//$JR_EXPR_ID=50$
                break;
            }
            case 51 : 
            {
                value = (java.lang.String)(((java.lang.String)field_DCB_FREEZE.getValue()));//$JR_EXPR_ID=51$
                break;
            }
            case 52 : 
            {
                value = (java.util.Date)(new java.util.Date());//$JR_EXPR_ID=52$
                break;
            }
            case 53 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_tot_private.getEstimatedValue()));//$JR_EXPR_ID=53$
                break;
            }
            case 54 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_tot_local.getEstimatedValue()));//$JR_EXPR_ID=54$
                break;
            }
            case 55 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_tot_private_ben.getEstimatedValue()));//$JR_EXPR_ID=55$
                break;
            }
            case 56 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_total_ben.getEstimatedValue()));//$JR_EXPR_ID=56$
                break;
            }
            case 57 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_total_pr.getEstimatedValue()));//$JR_EXPR_ID=57$
                break;
            }
            case 58 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_total_demand.getEstimatedValue()));//$JR_EXPR_ID=58$
                break;
            }
            case 59 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_total_collection.getEstimatedValue()));//$JR_EXPR_ID=59$
                break;
            }
            case 60 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_total_demand_ben.getEstimatedValue()));//$JR_EXPR_ID=60$
                break;
            }
            case 61 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_total_ledger_ben.getEstimatedValue()));//$JR_EXPR_ID=61$
                break;
            }
           default :
           {
           }
        }
        
        return value;
    }


}
