/*
 * Generated by JasperReports - 1/6/24 2:52 PM
 */
import net.sf.jasperreports.engine.*;
import net.sf.jasperreports.engine.fill.*;

import java.util.*;
import java.math.*;
import java.text.*;
import java.io.*;
import java.net.*;

import net.sf.jasperreports.engine.*;
import java.util.*;
import net.sf.jasperreports.engine.data.*;


/**
 *
 */
public class Division_Scheme_DCB_1704532944478_620984 extends JREvaluator
{


    /**
     *
     */
    private JRFillParameter parameter_IS_IGNORE_PAGINATION = null;
    private JRFillParameter parameter_REPORT_CONNECTION = null;
    private JRFillParameter parameter_year = null;
    private JRFillParameter parameter_ctxpath = null;
    private JRFillParameter parameter_REPORT_LOCALE = null;
    private JRFillParameter parameter_mvalue = null;
    private JRFillParameter parameter_REPORT_TIME_ZONE = null;
    private JRFillParameter parameter_REPORT_TEMPLATES = null;
    private JRFillParameter parameter_REPORT_MAX_COUNT = null;
    private JRFillParameter parameter_REPORT_SCRIPTLET = null;
    private JRFillParameter parameter_office_id = null;
    private JRFillParameter parameter_prv_year = null;
    private JRFillParameter parameter_office_name = null;
    private JRFillParameter parameter_prv_month = null;
    private JRFillParameter parameter_REPORT_FILE_RESOLVER = null;
    private JRFillParameter parameter_month = null;
    private JRFillParameter parameter_REPORT_FORMAT_FACTORY = null;
    private JRFillParameter parameter_REPORT_PARAMETERS_MAP = null;
    private JRFillParameter parameter_REPORT_RESOURCE_BUNDLE = null;
    private JRFillParameter parameter_REPORT_DATA_SOURCE = null;
    private JRFillParameter parameter_apryear = null;
    private JRFillParameter parameter_REPORT_CLASS_LOADER = null;
    private JRFillParameter parameter_REPORT_URL_HANDLER_FACTORY = null;
    private JRFillParameter parameter_REPORT_VIRTUALIZER = null;
    private JRFillField field_dmd_upto_prv_mnth_wc_9 = null;
    private JRFillField field_collection_upto = null;
    private JRFillField field_total = null;
    private JRFillField field_sch_name = null;
    private JRFillField field_balance = null;
    private JRFillField field_opening_bal_wc = null;
    private JRFillField field_dmdformonth = null;
    private JRFillField field_netdue = null;
    private JRFillField field_sch_sno = null;
    private JRFillVariable variable_PAGE_NUMBER = null;
    private JRFillVariable variable_COLUMN_NUMBER = null;
    private JRFillVariable variable_REPORT_COUNT = null;
    private JRFillVariable variable_PAGE_COUNT = null;
    private JRFillVariable variable_COLUMN_COUNT = null;
    private JRFillVariable variable_column3_sum = null;
    private JRFillVariable variable_column4_sum = null;
    private JRFillVariable variable_column5_sum = null;
    private JRFillVariable variable_column6_sum = null;
    private JRFillVariable variable_column7_sum = null;
    private JRFillVariable variable_column8_sum = null;
    private JRFillVariable variable_column9_sum = null;


    /**
     *
     */
    public void customizedInit(
        Map pm,
        Map fm,
        Map vm
        )
    {
        initParams(pm);
        initFields(fm);
        initVars(vm);
    }


    /**
     *
     */
    private void initParams(Map pm)
    {
        parameter_IS_IGNORE_PAGINATION = (JRFillParameter)pm.get("IS_IGNORE_PAGINATION");
        parameter_REPORT_CONNECTION = (JRFillParameter)pm.get("REPORT_CONNECTION");
        parameter_year = (JRFillParameter)pm.get("year");
        parameter_ctxpath = (JRFillParameter)pm.get("ctxpath");
        parameter_REPORT_LOCALE = (JRFillParameter)pm.get("REPORT_LOCALE");
        parameter_mvalue = (JRFillParameter)pm.get("mvalue");
        parameter_REPORT_TIME_ZONE = (JRFillParameter)pm.get("REPORT_TIME_ZONE");
        parameter_REPORT_TEMPLATES = (JRFillParameter)pm.get("REPORT_TEMPLATES");
        parameter_REPORT_MAX_COUNT = (JRFillParameter)pm.get("REPORT_MAX_COUNT");
        parameter_REPORT_SCRIPTLET = (JRFillParameter)pm.get("REPORT_SCRIPTLET");
        parameter_office_id = (JRFillParameter)pm.get("office_id");
        parameter_prv_year = (JRFillParameter)pm.get("prv_year");
        parameter_office_name = (JRFillParameter)pm.get("office_name");
        parameter_prv_month = (JRFillParameter)pm.get("prv_month");
        parameter_REPORT_FILE_RESOLVER = (JRFillParameter)pm.get("REPORT_FILE_RESOLVER");
        parameter_month = (JRFillParameter)pm.get("month");
        parameter_REPORT_FORMAT_FACTORY = (JRFillParameter)pm.get("REPORT_FORMAT_FACTORY");
        parameter_REPORT_PARAMETERS_MAP = (JRFillParameter)pm.get("REPORT_PARAMETERS_MAP");
        parameter_REPORT_RESOURCE_BUNDLE = (JRFillParameter)pm.get("REPORT_RESOURCE_BUNDLE");
        parameter_REPORT_DATA_SOURCE = (JRFillParameter)pm.get("REPORT_DATA_SOURCE");
        parameter_apryear = (JRFillParameter)pm.get("apryear");
        parameter_REPORT_CLASS_LOADER = (JRFillParameter)pm.get("REPORT_CLASS_LOADER");
        parameter_REPORT_URL_HANDLER_FACTORY = (JRFillParameter)pm.get("REPORT_URL_HANDLER_FACTORY");
        parameter_REPORT_VIRTUALIZER = (JRFillParameter)pm.get("REPORT_VIRTUALIZER");
    }


    /**
     *
     */
    private void initFields(Map fm)
    {
        field_dmd_upto_prv_mnth_wc_9 = (JRFillField)fm.get("dmd_upto_prv_mnth_wc_9");
        field_collection_upto = (JRFillField)fm.get("collection_upto");
        field_total = (JRFillField)fm.get("total");
        field_sch_name = (JRFillField)fm.get("sch_name");
        field_balance = (JRFillField)fm.get("balance");
        field_opening_bal_wc = (JRFillField)fm.get("opening_bal_wc");
        field_dmdformonth = (JRFillField)fm.get("dmdformonth");
        field_netdue = (JRFillField)fm.get("netdue");
        field_sch_sno = (JRFillField)fm.get("sch_sno");
    }


    /**
     *
     */
    private void initVars(Map vm)
    {
        variable_PAGE_NUMBER = (JRFillVariable)vm.get("PAGE_NUMBER");
        variable_COLUMN_NUMBER = (JRFillVariable)vm.get("COLUMN_NUMBER");
        variable_REPORT_COUNT = (JRFillVariable)vm.get("REPORT_COUNT");
        variable_PAGE_COUNT = (JRFillVariable)vm.get("PAGE_COUNT");
        variable_COLUMN_COUNT = (JRFillVariable)vm.get("COLUMN_COUNT");
        variable_column3_sum = (JRFillVariable)vm.get("column3_sum");
        variable_column4_sum = (JRFillVariable)vm.get("column4_sum");
        variable_column5_sum = (JRFillVariable)vm.get("column5_sum");
        variable_column6_sum = (JRFillVariable)vm.get("column6_sum");
        variable_column7_sum = (JRFillVariable)vm.get("column7_sum");
        variable_column8_sum = (JRFillVariable)vm.get("column8_sum");
        variable_column9_sum = (JRFillVariable)vm.get("column9_sum");
    }


    /**
     *
     */
    public Object evaluate(int id) throws Throwable
    {
        Object value = null;

        switch (id)
        {
            case 0 : 
            {
                value = (java.lang.Integer)(new Integer(1));//$JR_EXPR_ID=0$
                break;
            }
            case 1 : 
            {
                value = (java.lang.Integer)(new Integer(1));//$JR_EXPR_ID=1$
                break;
            }
            case 2 : 
            {
                value = (java.lang.Integer)(new Integer(1));//$JR_EXPR_ID=2$
                break;
            }
            case 3 : 
            {
                value = (java.lang.Integer)(new Integer(0));//$JR_EXPR_ID=3$
                break;
            }
            case 4 : 
            {
                value = (java.lang.Integer)(new Integer(1));//$JR_EXPR_ID=4$
                break;
            }
            case 5 : 
            {
                value = (java.lang.Integer)(new Integer(0));//$JR_EXPR_ID=5$
                break;
            }
            case 6 : 
            {
                value = (java.lang.Integer)(new Integer(1));//$JR_EXPR_ID=6$
                break;
            }
            case 7 : 
            {
                value = (java.lang.Integer)(new Integer(0));//$JR_EXPR_ID=7$
                break;
            }
            case 8 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_opening_bal_wc.getValue()));//$JR_EXPR_ID=8$
                break;
            }
            case 9 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_dmd_upto_prv_mnth_wc_9.getValue()));//$JR_EXPR_ID=9$
                break;
            }
            case 10 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_total.getValue()));//$JR_EXPR_ID=10$
                break;
            }
            case 11 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_collection_upto.getValue()));//$JR_EXPR_ID=11$
                break;
            }
            case 12 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_balance.getValue()));//$JR_EXPR_ID=12$
                break;
            }
            case 13 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_dmdformonth.getValue()));//$JR_EXPR_ID=13$
                break;
            }
            case 14 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_netdue.getValue()));//$JR_EXPR_ID=14$
                break;
            }
            case 15 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_office_name.getValue()));//$JR_EXPR_ID=15$
                break;
            }
            case 16 : 
            {
                value = (java.lang.String)("SCHEMEWISE DEMAND, COLLECTION AND BALANCE UPTO "+((java.lang.String)parameter_mvalue.getValue())+"/"+((java.lang.String)parameter_year.getValue()));//$JR_EXPR_ID=16$
                break;
            }
            case 17 : 
            {
                value = (java.lang.String)("Opening Balance as on 31.03."+((java.lang.String)parameter_apryear.getValue()));//$JR_EXPR_ID=17$
                break;
            }
            case 18 : 
            {
                value = (java.lang.String)("Collection upto "+ ((java.lang.String)parameter_month.getValue())+"/"+((java.lang.String)parameter_year.getValue()));//$JR_EXPR_ID=18$
                break;
            }
            case 19 : 
            {
                value = (java.lang.String)("Demand raised upto "+((java.lang.Integer)parameter_prv_month.getValue())+"/"+((java.lang.Integer)parameter_prv_year.getValue()));//$JR_EXPR_ID=19$
                break;
            }
            case 20 : 
            {
                value = (java.lang.String)("Demand for "+((java.lang.String)parameter_month.getValue())+"/"+((java.lang.String)parameter_year.getValue()));//$JR_EXPR_ID=20$
                break;
            }
            case 21 : 
            {
                value = (java.lang.Integer)(((java.lang.Integer)variable_REPORT_COUNT.getValue()));//$JR_EXPR_ID=21$
                break;
            }
            case 22 : 
            {
                value = (java.lang.String)(((java.lang.String)field_sch_name.getValue()));//$JR_EXPR_ID=22$
                break;
            }
            case 23 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_ctxpath.getValue())+"?process_code=22&office_id="+((java.lang.String)parameter_office_id.getValue())+"&fyear="+((java.lang.String)parameter_year.getValue())+"&fmonth="+((java.lang.String)parameter_month.getValue())+"&SCH_SNO="+((java.math.BigDecimal)field_sch_sno.getValue())+"&SCH_NAME="+((java.lang.String)field_sch_name.getValue())+"&office_name="+((java.lang.String)parameter_office_name.getValue()));//$JR_EXPR_ID=23$
                break;
            }
            case 24 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_opening_bal_wc.getValue()));//$JR_EXPR_ID=24$
                break;
            }
            case 25 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_dmd_upto_prv_mnth_wc_9.getValue()));//$JR_EXPR_ID=25$
                break;
            }
            case 26 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_total.getValue()));//$JR_EXPR_ID=26$
                break;
            }
            case 27 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_collection_upto.getValue()));//$JR_EXPR_ID=27$
                break;
            }
            case 28 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_balance.getValue()));//$JR_EXPR_ID=28$
                break;
            }
            case 29 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_dmdformonth.getValue()));//$JR_EXPR_ID=29$
                break;
            }
            case 30 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_netdue.getValue()));//$JR_EXPR_ID=30$
                break;
            }
            case 31 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_sch_sno.getValue()));//$JR_EXPR_ID=31$
                break;
            }
            case 32 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_ctxpath.getValue())+"?process_code=22&office_id="+((java.lang.String)parameter_office_id.getValue())+"&fyear="+((java.lang.String)parameter_year.getValue())+"&fmonth="+((java.lang.String)parameter_month.getValue())+"&SCH_SNO="+((java.math.BigDecimal)field_sch_sno.getValue())+"&SCH_NAME="+((java.lang.String)field_sch_name.getValue())+"&office_name="+((java.lang.String)parameter_office_name.getValue()));//$JR_EXPR_ID=32$
                break;
            }
            case 33 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_column3_sum.getValue()));//$JR_EXPR_ID=33$
                break;
            }
            case 34 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_column4_sum.getValue()));//$JR_EXPR_ID=34$
                break;
            }
            case 35 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_column5_sum.getValue()));//$JR_EXPR_ID=35$
                break;
            }
            case 36 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_column6_sum.getValue()));//$JR_EXPR_ID=36$
                break;
            }
            case 37 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_column7_sum.getValue()));//$JR_EXPR_ID=37$
                break;
            }
            case 38 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_column8_sum.getValue()));//$JR_EXPR_ID=38$
                break;
            }
            case 39 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_column9_sum.getValue()));//$JR_EXPR_ID=39$
                break;
            }
            case 40 : 
            {
                value = (java.lang.String)(" Total ");//$JR_EXPR_ID=40$
                break;
            }
           default :
           {
           }
        }
        
        return value;
    }


    /**
     *
     */
    public Object evaluateOld(int id) throws Throwable
    {
        Object value = null;

        switch (id)
        {
            case 0 : 
            {
                value = (java.lang.Integer)(new Integer(1));//$JR_EXPR_ID=0$
                break;
            }
            case 1 : 
            {
                value = (java.lang.Integer)(new Integer(1));//$JR_EXPR_ID=1$
                break;
            }
            case 2 : 
            {
                value = (java.lang.Integer)(new Integer(1));//$JR_EXPR_ID=2$
                break;
            }
            case 3 : 
            {
                value = (java.lang.Integer)(new Integer(0));//$JR_EXPR_ID=3$
                break;
            }
            case 4 : 
            {
                value = (java.lang.Integer)(new Integer(1));//$JR_EXPR_ID=4$
                break;
            }
            case 5 : 
            {
                value = (java.lang.Integer)(new Integer(0));//$JR_EXPR_ID=5$
                break;
            }
            case 6 : 
            {
                value = (java.lang.Integer)(new Integer(1));//$JR_EXPR_ID=6$
                break;
            }
            case 7 : 
            {
                value = (java.lang.Integer)(new Integer(0));//$JR_EXPR_ID=7$
                break;
            }
            case 8 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_opening_bal_wc.getOldValue()));//$JR_EXPR_ID=8$
                break;
            }
            case 9 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_dmd_upto_prv_mnth_wc_9.getOldValue()));//$JR_EXPR_ID=9$
                break;
            }
            case 10 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_total.getOldValue()));//$JR_EXPR_ID=10$
                break;
            }
            case 11 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_collection_upto.getOldValue()));//$JR_EXPR_ID=11$
                break;
            }
            case 12 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_balance.getOldValue()));//$JR_EXPR_ID=12$
                break;
            }
            case 13 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_dmdformonth.getOldValue()));//$JR_EXPR_ID=13$
                break;
            }
            case 14 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_netdue.getOldValue()));//$JR_EXPR_ID=14$
                break;
            }
            case 15 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_office_name.getValue()));//$JR_EXPR_ID=15$
                break;
            }
            case 16 : 
            {
                value = (java.lang.String)("SCHEMEWISE DEMAND, COLLECTION AND BALANCE UPTO "+((java.lang.String)parameter_mvalue.getValue())+"/"+((java.lang.String)parameter_year.getValue()));//$JR_EXPR_ID=16$
                break;
            }
            case 17 : 
            {
                value = (java.lang.String)("Opening Balance as on 31.03."+((java.lang.String)parameter_apryear.getValue()));//$JR_EXPR_ID=17$
                break;
            }
            case 18 : 
            {
                value = (java.lang.String)("Collection upto "+ ((java.lang.String)parameter_month.getValue())+"/"+((java.lang.String)parameter_year.getValue()));//$JR_EXPR_ID=18$
                break;
            }
            case 19 : 
            {
                value = (java.lang.String)("Demand raised upto "+((java.lang.Integer)parameter_prv_month.getValue())+"/"+((java.lang.Integer)parameter_prv_year.getValue()));//$JR_EXPR_ID=19$
                break;
            }
            case 20 : 
            {
                value = (java.lang.String)("Demand for "+((java.lang.String)parameter_month.getValue())+"/"+((java.lang.String)parameter_year.getValue()));//$JR_EXPR_ID=20$
                break;
            }
            case 21 : 
            {
                value = (java.lang.Integer)(((java.lang.Integer)variable_REPORT_COUNT.getOldValue()));//$JR_EXPR_ID=21$
                break;
            }
            case 22 : 
            {
                value = (java.lang.String)(((java.lang.String)field_sch_name.getOldValue()));//$JR_EXPR_ID=22$
                break;
            }
            case 23 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_ctxpath.getValue())+"?process_code=22&office_id="+((java.lang.String)parameter_office_id.getValue())+"&fyear="+((java.lang.String)parameter_year.getValue())+"&fmonth="+((java.lang.String)parameter_month.getValue())+"&SCH_SNO="+((java.math.BigDecimal)field_sch_sno.getOldValue())+"&SCH_NAME="+((java.lang.String)field_sch_name.getOldValue())+"&office_name="+((java.lang.String)parameter_office_name.getValue()));//$JR_EXPR_ID=23$
                break;
            }
            case 24 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_opening_bal_wc.getOldValue()));//$JR_EXPR_ID=24$
                break;
            }
            case 25 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_dmd_upto_prv_mnth_wc_9.getOldValue()));//$JR_EXPR_ID=25$
                break;
            }
            case 26 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_total.getOldValue()));//$JR_EXPR_ID=26$
                break;
            }
            case 27 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_collection_upto.getOldValue()));//$JR_EXPR_ID=27$
                break;
            }
            case 28 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_balance.getOldValue()));//$JR_EXPR_ID=28$
                break;
            }
            case 29 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_dmdformonth.getOldValue()));//$JR_EXPR_ID=29$
                break;
            }
            case 30 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_netdue.getOldValue()));//$JR_EXPR_ID=30$
                break;
            }
            case 31 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_sch_sno.getOldValue()));//$JR_EXPR_ID=31$
                break;
            }
            case 32 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_ctxpath.getValue())+"?process_code=22&office_id="+((java.lang.String)parameter_office_id.getValue())+"&fyear="+((java.lang.String)parameter_year.getValue())+"&fmonth="+((java.lang.String)parameter_month.getValue())+"&SCH_SNO="+((java.math.BigDecimal)field_sch_sno.getOldValue())+"&SCH_NAME="+((java.lang.String)field_sch_name.getOldValue())+"&office_name="+((java.lang.String)parameter_office_name.getValue()));//$JR_EXPR_ID=32$
                break;
            }
            case 33 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_column3_sum.getOldValue()));//$JR_EXPR_ID=33$
                break;
            }
            case 34 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_column4_sum.getOldValue()));//$JR_EXPR_ID=34$
                break;
            }
            case 35 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_column5_sum.getOldValue()));//$JR_EXPR_ID=35$
                break;
            }
            case 36 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_column6_sum.getOldValue()));//$JR_EXPR_ID=36$
                break;
            }
            case 37 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_column7_sum.getOldValue()));//$JR_EXPR_ID=37$
                break;
            }
            case 38 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_column8_sum.getOldValue()));//$JR_EXPR_ID=38$
                break;
            }
            case 39 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_column9_sum.getOldValue()));//$JR_EXPR_ID=39$
                break;
            }
            case 40 : 
            {
                value = (java.lang.String)(" Total ");//$JR_EXPR_ID=40$
                break;
            }
           default :
           {
           }
        }
        
        return value;
    }


    /**
     *
     */
    public Object evaluateEstimated(int id) throws Throwable
    {
        Object value = null;

        switch (id)
        {
            case 0 : 
            {
                value = (java.lang.Integer)(new Integer(1));//$JR_EXPR_ID=0$
                break;
            }
            case 1 : 
            {
                value = (java.lang.Integer)(new Integer(1));//$JR_EXPR_ID=1$
                break;
            }
            case 2 : 
            {
                value = (java.lang.Integer)(new Integer(1));//$JR_EXPR_ID=2$
                break;
            }
            case 3 : 
            {
                value = (java.lang.Integer)(new Integer(0));//$JR_EXPR_ID=3$
                break;
            }
            case 4 : 
            {
                value = (java.lang.Integer)(new Integer(1));//$JR_EXPR_ID=4$
                break;
            }
            case 5 : 
            {
                value = (java.lang.Integer)(new Integer(0));//$JR_EXPR_ID=5$
                break;
            }
            case 6 : 
            {
                value = (java.lang.Integer)(new Integer(1));//$JR_EXPR_ID=6$
                break;
            }
            case 7 : 
            {
                value = (java.lang.Integer)(new Integer(0));//$JR_EXPR_ID=7$
                break;
            }
            case 8 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_opening_bal_wc.getValue()));//$JR_EXPR_ID=8$
                break;
            }
            case 9 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_dmd_upto_prv_mnth_wc_9.getValue()));//$JR_EXPR_ID=9$
                break;
            }
            case 10 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_total.getValue()));//$JR_EXPR_ID=10$
                break;
            }
            case 11 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_collection_upto.getValue()));//$JR_EXPR_ID=11$
                break;
            }
            case 12 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_balance.getValue()));//$JR_EXPR_ID=12$
                break;
            }
            case 13 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_dmdformonth.getValue()));//$JR_EXPR_ID=13$
                break;
            }
            case 14 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_netdue.getValue()));//$JR_EXPR_ID=14$
                break;
            }
            case 15 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_office_name.getValue()));//$JR_EXPR_ID=15$
                break;
            }
            case 16 : 
            {
                value = (java.lang.String)("SCHEMEWISE DEMAND, COLLECTION AND BALANCE UPTO "+((java.lang.String)parameter_mvalue.getValue())+"/"+((java.lang.String)parameter_year.getValue()));//$JR_EXPR_ID=16$
                break;
            }
            case 17 : 
            {
                value = (java.lang.String)("Opening Balance as on 31.03."+((java.lang.String)parameter_apryear.getValue()));//$JR_EXPR_ID=17$
                break;
            }
            case 18 : 
            {
                value = (java.lang.String)("Collection upto "+ ((java.lang.String)parameter_month.getValue())+"/"+((java.lang.String)parameter_year.getValue()));//$JR_EXPR_ID=18$
                break;
            }
            case 19 : 
            {
                value = (java.lang.String)("Demand raised upto "+((java.lang.Integer)parameter_prv_month.getValue())+"/"+((java.lang.Integer)parameter_prv_year.getValue()));//$JR_EXPR_ID=19$
                break;
            }
            case 20 : 
            {
                value = (java.lang.String)("Demand for "+((java.lang.String)parameter_month.getValue())+"/"+((java.lang.String)parameter_year.getValue()));//$JR_EXPR_ID=20$
                break;
            }
            case 21 : 
            {
                value = (java.lang.Integer)(((java.lang.Integer)variable_REPORT_COUNT.getEstimatedValue()));//$JR_EXPR_ID=21$
                break;
            }
            case 22 : 
            {
                value = (java.lang.String)(((java.lang.String)field_sch_name.getValue()));//$JR_EXPR_ID=22$
                break;
            }
            case 23 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_ctxpath.getValue())+"?process_code=22&office_id="+((java.lang.String)parameter_office_id.getValue())+"&fyear="+((java.lang.String)parameter_year.getValue())+"&fmonth="+((java.lang.String)parameter_month.getValue())+"&SCH_SNO="+((java.math.BigDecimal)field_sch_sno.getValue())+"&SCH_NAME="+((java.lang.String)field_sch_name.getValue())+"&office_name="+((java.lang.String)parameter_office_name.getValue()));//$JR_EXPR_ID=23$
                break;
            }
            case 24 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_opening_bal_wc.getValue()));//$JR_EXPR_ID=24$
                break;
            }
            case 25 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_dmd_upto_prv_mnth_wc_9.getValue()));//$JR_EXPR_ID=25$
                break;
            }
            case 26 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_total.getValue()));//$JR_EXPR_ID=26$
                break;
            }
            case 27 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_collection_upto.getValue()));//$JR_EXPR_ID=27$
                break;
            }
            case 28 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_balance.getValue()));//$JR_EXPR_ID=28$
                break;
            }
            case 29 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_dmdformonth.getValue()));//$JR_EXPR_ID=29$
                break;
            }
            case 30 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_netdue.getValue()));//$JR_EXPR_ID=30$
                break;
            }
            case 31 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_sch_sno.getValue()));//$JR_EXPR_ID=31$
                break;
            }
            case 32 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_ctxpath.getValue())+"?process_code=22&office_id="+((java.lang.String)parameter_office_id.getValue())+"&fyear="+((java.lang.String)parameter_year.getValue())+"&fmonth="+((java.lang.String)parameter_month.getValue())+"&SCH_SNO="+((java.math.BigDecimal)field_sch_sno.getValue())+"&SCH_NAME="+((java.lang.String)field_sch_name.getValue())+"&office_name="+((java.lang.String)parameter_office_name.getValue()));//$JR_EXPR_ID=32$
                break;
            }
            case 33 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_column3_sum.getEstimatedValue()));//$JR_EXPR_ID=33$
                break;
            }
            case 34 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_column4_sum.getEstimatedValue()));//$JR_EXPR_ID=34$
                break;
            }
            case 35 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_column5_sum.getEstimatedValue()));//$JR_EXPR_ID=35$
                break;
            }
            case 36 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_column6_sum.getEstimatedValue()));//$JR_EXPR_ID=36$
                break;
            }
            case 37 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_column7_sum.getEstimatedValue()));//$JR_EXPR_ID=37$
                break;
            }
            case 38 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_column8_sum.getEstimatedValue()));//$JR_EXPR_ID=38$
                break;
            }
            case 39 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_column9_sum.getEstimatedValue()));//$JR_EXPR_ID=39$
                break;
            }
            case 40 : 
            {
                value = (java.lang.String)(" Total ");//$JR_EXPR_ID=40$
                break;
            }
           default :
           {
           }
        }
        
        return value;
    }


}
