/*
 * Generated by JasperReports - 13/7/23 6:44 PM
 */
import net.sf.jasperreports.engine.*;
import net.sf.jasperreports.engine.fill.*;

import java.util.*;
import java.math.*;
import java.text.*;
import java.io.*;
import java.net.*;

import net.sf.jasperreports.engine.*;
import java.util.*;
import net.sf.jasperreports.engine.data.*;


/**
 *
 */
public class PMS_DCB_DMD_COLLECTION_1689254066220_657984 extends JREvaluator
{


    /**
     *
     */
    private JRFillParameter parameter_REPORT_CONNECTION = null;
    private JRFillParameter parameter_ctxpath = null;
    private JRFillParameter parameter_mvalue = null;
    private JRFillParameter parameter_REPORT_TIME_ZONE = null;
    private JRFillParameter parameter_REPORT_TEMPLATES = null;
    private JRFillParameter parameter_SUBREPORT_DIR = null;
    private JRFillParameter parameter_REPORT_MAX_COUNT = null;
    private JRFillParameter parameter_year1 = null;
    private JRFillParameter parameter_year2 = null;
    private JRFillParameter parameter_REPORT_SCRIPTLET = null;
    private JRFillParameter parameter_office_id = null;
    private JRFillParameter parameter_REPORT_PARAMETERS_MAP = null;
    private JRFillParameter parameter_REPORT_RESOURCE_BUNDLE = null;
    private JRFillParameter parameter_REPORT_DATA_SOURCE = null;
    private JRFillParameter parameter_IS_IGNORE_PAGINATION = null;
    private JRFillParameter parameter_month1 = null;
    private JRFillParameter parameter_month2 = null;
    private JRFillParameter parameter_REPORT_LOCALE = null;
    private JRFillParameter parameter_count = null;
    private JRFillParameter parameter_office_name = null;
    private JRFillParameter parameter_REPORT_FILE_RESOLVER = null;
    private JRFillParameter parameter_REPORT_FORMAT_FACTORY = null;
    private JRFillParameter parameter_days = null;
    private JRFillParameter parameter_REPORT_CLASS_LOADER = null;
    private JRFillParameter parameter_REPORT_URL_HANDLER_FACTORY = null;
    private JRFillParameter parameter_REPORT_VIRTUALIZER = null;
    private JRFillField field_ADD_CHARGES_WC = null;
    private JRFillField field_MINUS_CHARGES_WC = null;
    private JRFillField field_BENEFICIARY_TYPE_ID = null;
    private JRFillField field_dd = null;
    private JRFillField field_BENSO = null;
    private JRFillField field_year = null;
    private JRFillField field_mval = null;
    private JRFillField field_ben_type_id = null;
    private JRFillField field_BILL_MONTH = null;
    private JRFillField field_TOTAL_AMT = null;
    private JRFillField field_ben_type_desc = null;
    private JRFillField field_month = null;
    private JRFillField field_beneficiary_sno = null;
    private JRFillField field_BENEFICIARY_NAME = null;
    private JRFillField field_qty = null;
    private JRFillField field_tot = null;
    private JRFillField field_BILL_YEAR = null;
    private JRFillVariable variable_PAGE_NUMBER = null;
    private JRFillVariable variable_COLUMN_NUMBER = null;
    private JRFillVariable variable_REPORT_COUNT = null;
    private JRFillVariable variable_PAGE_COUNT = null;
    private JRFillVariable variable_COLUMN_COUNT = null;
    private JRFillVariable variable_bt_COUNT = null;
    private JRFillVariable variable_ben_COUNT = null;
    private JRFillVariable variable_bc = null;
    private JRFillVariable variable_rc = null;
    private JRFillVariable variable_net_demand = null;
    private JRFillVariable variable_type_demand = null;
    private JRFillVariable variable_net_collection = null;
    private JRFillVariable variable_type_collection = null;
    private JRFillVariable variable_type_qty = null;
    private JRFillVariable variable_net_qty = null;
    private JRFillVariable variable_net_collection_1 = null;
    private JRFillVariable variable_net_collection_2 = null;
    private JRFillVariable variable_total_colection = null;
    private JRFillVariable variable_type_collection_add = null;
    private JRFillVariable variable_type_collection_sub = null;
    private JRFillVariable variable_type_collection_net = null;
    private JRFillVariable variable_net_collection_net = null;


    /**
     *
     */
    public void customizedInit(
        Map pm,
        Map fm,
        Map vm
        )
    {
        initParams(pm);
        initFields(fm);
        initVars(vm);
    }


    /**
     *
     */
    private void initParams(Map pm)
    {
        parameter_REPORT_CONNECTION = (JRFillParameter)pm.get("REPORT_CONNECTION");
        parameter_ctxpath = (JRFillParameter)pm.get("ctxpath");
        parameter_mvalue = (JRFillParameter)pm.get("mvalue");
        parameter_REPORT_TIME_ZONE = (JRFillParameter)pm.get("REPORT_TIME_ZONE");
        parameter_REPORT_TEMPLATES = (JRFillParameter)pm.get("REPORT_TEMPLATES");
        parameter_SUBREPORT_DIR = (JRFillParameter)pm.get("SUBREPORT_DIR");
        parameter_REPORT_MAX_COUNT = (JRFillParameter)pm.get("REPORT_MAX_COUNT");
        parameter_year1 = (JRFillParameter)pm.get("year1");
        parameter_year2 = (JRFillParameter)pm.get("year2");
        parameter_REPORT_SCRIPTLET = (JRFillParameter)pm.get("REPORT_SCRIPTLET");
        parameter_office_id = (JRFillParameter)pm.get("office_id");
        parameter_REPORT_PARAMETERS_MAP = (JRFillParameter)pm.get("REPORT_PARAMETERS_MAP");
        parameter_REPORT_RESOURCE_BUNDLE = (JRFillParameter)pm.get("REPORT_RESOURCE_BUNDLE");
        parameter_REPORT_DATA_SOURCE = (JRFillParameter)pm.get("REPORT_DATA_SOURCE");
        parameter_IS_IGNORE_PAGINATION = (JRFillParameter)pm.get("IS_IGNORE_PAGINATION");
        parameter_month1 = (JRFillParameter)pm.get("month1");
        parameter_month2 = (JRFillParameter)pm.get("month2");
        parameter_REPORT_LOCALE = (JRFillParameter)pm.get("REPORT_LOCALE");
        parameter_count = (JRFillParameter)pm.get("count");
        parameter_office_name = (JRFillParameter)pm.get("office_name");
        parameter_REPORT_FILE_RESOLVER = (JRFillParameter)pm.get("REPORT_FILE_RESOLVER");
        parameter_REPORT_FORMAT_FACTORY = (JRFillParameter)pm.get("REPORT_FORMAT_FACTORY");
        parameter_days = (JRFillParameter)pm.get("days");
        parameter_REPORT_CLASS_LOADER = (JRFillParameter)pm.get("REPORT_CLASS_LOADER");
        parameter_REPORT_URL_HANDLER_FACTORY = (JRFillParameter)pm.get("REPORT_URL_HANDLER_FACTORY");
        parameter_REPORT_VIRTUALIZER = (JRFillParameter)pm.get("REPORT_VIRTUALIZER");
    }


    /**
     *
     */
    private void initFields(Map fm)
    {
        field_ADD_CHARGES_WC = (JRFillField)fm.get("ADD_CHARGES_WC");
        field_MINUS_CHARGES_WC = (JRFillField)fm.get("MINUS_CHARGES_WC");
        field_BENEFICIARY_TYPE_ID = (JRFillField)fm.get("BENEFICIARY_TYPE_ID");
        field_dd = (JRFillField)fm.get("dd");
        field_BENSO = (JRFillField)fm.get("BENSO");
        field_year = (JRFillField)fm.get("year");
        field_mval = (JRFillField)fm.get("mval");
        field_ben_type_id = (JRFillField)fm.get("ben_type_id");
        field_BILL_MONTH = (JRFillField)fm.get("BILL_MONTH");
        field_TOTAL_AMT = (JRFillField)fm.get("TOTAL_AMT");
        field_ben_type_desc = (JRFillField)fm.get("ben_type_desc");
        field_month = (JRFillField)fm.get("month");
        field_beneficiary_sno = (JRFillField)fm.get("beneficiary_sno");
        field_BENEFICIARY_NAME = (JRFillField)fm.get("BENEFICIARY_NAME");
        field_qty = (JRFillField)fm.get("qty");
        field_tot = (JRFillField)fm.get("tot");
        field_BILL_YEAR = (JRFillField)fm.get("BILL_YEAR");
    }


    /**
     *
     */
    private void initVars(Map vm)
    {
        variable_PAGE_NUMBER = (JRFillVariable)vm.get("PAGE_NUMBER");
        variable_COLUMN_NUMBER = (JRFillVariable)vm.get("COLUMN_NUMBER");
        variable_REPORT_COUNT = (JRFillVariable)vm.get("REPORT_COUNT");
        variable_PAGE_COUNT = (JRFillVariable)vm.get("PAGE_COUNT");
        variable_COLUMN_COUNT = (JRFillVariable)vm.get("COLUMN_COUNT");
        variable_bt_COUNT = (JRFillVariable)vm.get("bt_COUNT");
        variable_ben_COUNT = (JRFillVariable)vm.get("ben_COUNT");
        variable_bc = (JRFillVariable)vm.get("bc");
        variable_rc = (JRFillVariable)vm.get("rc");
        variable_net_demand = (JRFillVariable)vm.get("net_demand");
        variable_type_demand = (JRFillVariable)vm.get("type_demand");
        variable_net_collection = (JRFillVariable)vm.get("net_collection");
        variable_type_collection = (JRFillVariable)vm.get("type_collection");
        variable_type_qty = (JRFillVariable)vm.get("type_qty");
        variable_net_qty = (JRFillVariable)vm.get("net_qty");
        variable_net_collection_1 = (JRFillVariable)vm.get("net_collection_1");
        variable_net_collection_2 = (JRFillVariable)vm.get("net_collection_2");
        variable_total_colection = (JRFillVariable)vm.get("total_colection");
        variable_type_collection_add = (JRFillVariable)vm.get("type_collection_add");
        variable_type_collection_sub = (JRFillVariable)vm.get("type_collection_sub");
        variable_type_collection_net = (JRFillVariable)vm.get("type_collection_net");
        variable_net_collection_net = (JRFillVariable)vm.get("net_collection_net");
    }


    /**
     *
     */
    public Object evaluate(int id) throws Throwable
    {
        Object value = null;

        switch (id)
        {
            case 0 : 
            {
                value = (java.lang.String)("D:\\NIC Source\\twadonline\\WebContent\\WEB-INF\\ReportSrc\\");//$JR_EXPR_ID=0$
                break;
            }
            case 1 : 
            {
                value = (java.lang.Integer)(new Integer(1));//$JR_EXPR_ID=1$
                break;
            }
            case 2 : 
            {
                value = (java.lang.Integer)(new Integer(1));//$JR_EXPR_ID=2$
                break;
            }
            case 3 : 
            {
                value = (java.lang.Integer)(new Integer(1));//$JR_EXPR_ID=3$
                break;
            }
            case 4 : 
            {
                value = (java.lang.Integer)(new Integer(0));//$JR_EXPR_ID=4$
                break;
            }
            case 5 : 
            {
                value = (java.lang.Integer)(new Integer(1));//$JR_EXPR_ID=5$
                break;
            }
            case 6 : 
            {
                value = (java.lang.Integer)(new Integer(0));//$JR_EXPR_ID=6$
                break;
            }
            case 7 : 
            {
                value = (java.lang.Integer)(new Integer(1));//$JR_EXPR_ID=7$
                break;
            }
            case 8 : 
            {
                value = (java.lang.Integer)(new Integer(0));//$JR_EXPR_ID=8$
                break;
            }
            case 9 : 
            {
                value = (java.lang.Integer)(new Integer(1));//$JR_EXPR_ID=9$
                break;
            }
            case 10 : 
            {
                value = (java.lang.Integer)(new Integer(0));//$JR_EXPR_ID=10$
                break;
            }
            case 11 : 
            {
                value = (java.lang.Integer)(new Integer(1));//$JR_EXPR_ID=11$
                break;
            }
            case 12 : 
            {
                value = (java.lang.Integer)(new Integer(0));//$JR_EXPR_ID=12$
                break;
            }
            case 13 : 
            {
                value = (java.lang.Integer)(((java.lang.Integer)variable_REPORT_COUNT.getValue()));//$JR_EXPR_ID=13$
                break;
            }
            case 14 : 
            {
                value = (java.lang.Object)(((java.lang.Integer)variable_REPORT_COUNT.getValue()));//$JR_EXPR_ID=14$
                break;
            }
            case 15 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_dd.getValue()));//$JR_EXPR_ID=15$
                break;
            }
            case 16 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_dd.getValue()));//$JR_EXPR_ID=16$
                break;
            }
            case 17 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_tot.getValue()));//$JR_EXPR_ID=17$
                break;
            }
            case 18 : 
            {
                value = (java.math.BigDecimal)(( ((java.math.BigDecimal)field_tot.getValue())==null ? new java.math.BigDecimal(0) : ((java.math.BigDecimal)field_tot.getValue())));//$JR_EXPR_ID=18$
                break;
            }
            case 19 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_qty.getValue()));//$JR_EXPR_ID=19$
                break;
            }
            case 20 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_qty.getValue()));//$JR_EXPR_ID=20$
                break;
            }
            case 21 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_ADD_CHARGES_WC.getValue()));//$JR_EXPR_ID=21$
                break;
            }
            case 22 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_MINUS_CHARGES_WC.getValue()));//$JR_EXPR_ID=22$
                break;
            }
            case 23 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_TOTAL_AMT.getValue()).add( ((java.math.BigDecimal)field_MINUS_CHARGES_WC.getValue()) ));//$JR_EXPR_ID=23$
                break;
            }
            case 24 : 
            {
                value = (java.math.BigDecimal)(( ((java.math.BigDecimal)field_ADD_CHARGES_WC.getValue())==null ? new java.math.BigDecimal(0) : ((java.math.BigDecimal)field_ADD_CHARGES_WC.getValue()) ));//$JR_EXPR_ID=24$
                break;
            }
            case 25 : 
            {
                value = (java.math.BigDecimal)(( ((java.math.BigDecimal)field_MINUS_CHARGES_WC.getValue())==null ? new java.math.BigDecimal(0) : ((java.math.BigDecimal)field_MINUS_CHARGES_WC.getValue()) ));//$JR_EXPR_ID=25$
                break;
            }
            case 26 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_TOTAL_AMT.getValue()));//$JR_EXPR_ID=26$
                break;
            }
            case 27 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_TOTAL_AMT.getValue()));//$JR_EXPR_ID=27$
                break;
            }
            case 28 : 
            {
                value = (java.lang.Object)(((java.math.BigDecimal)field_BENEFICIARY_TYPE_ID.getValue()));//$JR_EXPR_ID=28$
                break;
            }
            case 29 : 
            {
                value = (java.lang.String)(((java.lang.String)field_ben_type_desc.getValue()));//$JR_EXPR_ID=29$
                break;
            }
            case 30 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_type_collection.getValue()));//$JR_EXPR_ID=30$
                break;
            }
            case 31 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_type_demand.getValue()));//$JR_EXPR_ID=31$
                break;
            }
            case 32 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_type_qty.getValue()));//$JR_EXPR_ID=32$
                break;
            }
            case 33 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_type_collection_add.getValue()));//$JR_EXPR_ID=33$
                break;
            }
            case 34 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_type_collection_net.getValue()).add(((java.math.BigDecimal)variable_type_collection_sub.getValue())));//$JR_EXPR_ID=34$
                break;
            }
            case 35 : 
            {
                value = (java.lang.String)(((java.lang.String)field_ben_type_desc.getValue()) +" Total");//$JR_EXPR_ID=35$
                break;
            }
            case 36 : 
            {
                value = (java.lang.Object)(((java.math.BigDecimal)field_BENSO.getValue()));//$JR_EXPR_ID=36$
                break;
            }
            case 37 : 
            {
                value = (java.lang.String)(((java.lang.String)field_BENEFICIARY_NAME.getValue())+"("+ ((java.math.BigDecimal)field_BENSO.getValue())+")");//$JR_EXPR_ID=37$
                break;
            }
            case 38 : 
            {
                value = (java.lang.Boolean)(new Boolean (!((java.lang.String)parameter_count.getValue()).equals("1")));//$JR_EXPR_ID=38$
                break;
            }
            case 39 : 
            {
                value = (java.lang.Boolean)(new Boolean (!((java.lang.String)parameter_count.getValue()).equals("1")));//$JR_EXPR_ID=39$
                break;
            }
            case 40 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_office_name.getValue()));//$JR_EXPR_ID=40$
                break;
            }
            case 41 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_mvalue.getValue()));//$JR_EXPR_ID=41$
                break;
            }
            case 42 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_dd.getValue()));//$JR_EXPR_ID=42$
                break;
            }
            case 43 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_TOTAL_AMT.getValue()).add(((java.math.BigDecimal)field_MINUS_CHARGES_WC.getValue())));//$JR_EXPR_ID=43$
                break;
            }
            case 44 : 
            {
                value = (java.lang.Boolean)(new Boolean (!((java.lang.String)parameter_count.getValue()).equals("1")));//$JR_EXPR_ID=44$
                break;
            }
            case 45 : 
            {
                value = (java.lang.String)(((java.lang.String)field_mval.getValue()));//$JR_EXPR_ID=45$
                break;
            }
            case 46 : 
            {
                value = (java.lang.Boolean)(new Boolean (!((java.lang.String)parameter_count.getValue()).equals("1")));//$JR_EXPR_ID=46$
                break;
            }
            case 47 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_year.getValue()));//$JR_EXPR_ID=47$
                break;
            }
            case 48 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_qty.getValue()));//$JR_EXPR_ID=48$
                break;
            }
            case 49 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_ADD_CHARGES_WC.getValue()));//$JR_EXPR_ID=49$
                break;
            }
            case 50 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_tot.getValue()));//$JR_EXPR_ID=50$
                break;
            }
            case 51 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_net_collection.getValue()));//$JR_EXPR_ID=51$
                break;
            }
            case 52 : 
            {
                value = (java.lang.String)("Grand Total");//$JR_EXPR_ID=52$
                break;
            }
            case 53 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_net_demand.getValue()));//$JR_EXPR_ID=53$
                break;
            }
            case 54 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_net_qty.getValue()));//$JR_EXPR_ID=54$
                break;
            }
            case 55 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_net_collection_1.getValue()));//$JR_EXPR_ID=55$
                break;
            }
            case 56 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_net_collection_net.getValue()).add(((java.math.BigDecimal)variable_net_collection_2.getValue())));//$JR_EXPR_ID=56$
                break;
            }
            case 57 : 
            {
                value = (java.lang.Object)(((java.lang.String)parameter_office_id.getValue()));//$JR_EXPR_ID=57$
                break;
            }
            case 58 : 
            {
                value = (java.lang.Object)(((java.lang.String)parameter_month1.getValue()));//$JR_EXPR_ID=58$
                break;
            }
            case 59 : 
            {
                value = (java.lang.Object)(((java.lang.String)parameter_office_name.getValue()));//$JR_EXPR_ID=59$
                break;
            }
            case 60 : 
            {
                value = (java.lang.Object)(((java.lang.String)parameter_month2.getValue()));//$JR_EXPR_ID=60$
                break;
            }
            case 61 : 
            {
                value = (java.lang.Object)(((java.lang.String)parameter_ctxpath.getValue()));//$JR_EXPR_ID=61$
                break;
            }
            case 62 : 
            {
                value = (java.lang.Object)(((java.lang.String)parameter_count.getValue()));//$JR_EXPR_ID=62$
                break;
            }
            case 63 : 
            {
                value = (java.lang.Object)(((java.lang.String)parameter_mvalue.getValue()));//$JR_EXPR_ID=63$
                break;
            }
            case 64 : 
            {
                value = (java.lang.Object)(((java.lang.Integer)parameter_days.getValue()));//$JR_EXPR_ID=64$
                break;
            }
            case 65 : 
            {
                value = (java.lang.Object)(((java.lang.String)parameter_SUBREPORT_DIR.getValue()));//$JR_EXPR_ID=65$
                break;
            }
            case 66 : 
            {
                value = (java.lang.Object)(((java.lang.String)parameter_year1.getValue()));//$JR_EXPR_ID=66$
                break;
            }
            case 67 : 
            {
                value = (java.lang.Object)(((java.lang.String)parameter_year2.getValue()));//$JR_EXPR_ID=67$
                break;
            }
            case 68 : 
            {
                value = (java.sql.Connection)(((java.sql.Connection)parameter_REPORT_CONNECTION.getValue()));//$JR_EXPR_ID=68$
                break;
            }
            case 69 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_ctxpath.getValue()) + "PMS_DCB_DMD_COLLECTION_SUM.jasper");//$JR_EXPR_ID=69$
                break;
            }
           default :
           {
           }
        }
        
        return value;
    }


    /**
     *
     */
    public Object evaluateOld(int id) throws Throwable
    {
        Object value = null;

        switch (id)
        {
            case 0 : 
            {
                value = (java.lang.String)("D:\\NIC Source\\twadonline\\WebContent\\WEB-INF\\ReportSrc\\");//$JR_EXPR_ID=0$
                break;
            }
            case 1 : 
            {
                value = (java.lang.Integer)(new Integer(1));//$JR_EXPR_ID=1$
                break;
            }
            case 2 : 
            {
                value = (java.lang.Integer)(new Integer(1));//$JR_EXPR_ID=2$
                break;
            }
            case 3 : 
            {
                value = (java.lang.Integer)(new Integer(1));//$JR_EXPR_ID=3$
                break;
            }
            case 4 : 
            {
                value = (java.lang.Integer)(new Integer(0));//$JR_EXPR_ID=4$
                break;
            }
            case 5 : 
            {
                value = (java.lang.Integer)(new Integer(1));//$JR_EXPR_ID=5$
                break;
            }
            case 6 : 
            {
                value = (java.lang.Integer)(new Integer(0));//$JR_EXPR_ID=6$
                break;
            }
            case 7 : 
            {
                value = (java.lang.Integer)(new Integer(1));//$JR_EXPR_ID=7$
                break;
            }
            case 8 : 
            {
                value = (java.lang.Integer)(new Integer(0));//$JR_EXPR_ID=8$
                break;
            }
            case 9 : 
            {
                value = (java.lang.Integer)(new Integer(1));//$JR_EXPR_ID=9$
                break;
            }
            case 10 : 
            {
                value = (java.lang.Integer)(new Integer(0));//$JR_EXPR_ID=10$
                break;
            }
            case 11 : 
            {
                value = (java.lang.Integer)(new Integer(1));//$JR_EXPR_ID=11$
                break;
            }
            case 12 : 
            {
                value = (java.lang.Integer)(new Integer(0));//$JR_EXPR_ID=12$
                break;
            }
            case 13 : 
            {
                value = (java.lang.Integer)(((java.lang.Integer)variable_REPORT_COUNT.getOldValue()));//$JR_EXPR_ID=13$
                break;
            }
            case 14 : 
            {
                value = (java.lang.Object)(((java.lang.Integer)variable_REPORT_COUNT.getOldValue()));//$JR_EXPR_ID=14$
                break;
            }
            case 15 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_dd.getOldValue()));//$JR_EXPR_ID=15$
                break;
            }
            case 16 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_dd.getOldValue()));//$JR_EXPR_ID=16$
                break;
            }
            case 17 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_tot.getOldValue()));//$JR_EXPR_ID=17$
                break;
            }
            case 18 : 
            {
                value = (java.math.BigDecimal)(( ((java.math.BigDecimal)field_tot.getOldValue())==null ? new java.math.BigDecimal(0) : ((java.math.BigDecimal)field_tot.getOldValue())));//$JR_EXPR_ID=18$
                break;
            }
            case 19 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_qty.getOldValue()));//$JR_EXPR_ID=19$
                break;
            }
            case 20 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_qty.getOldValue()));//$JR_EXPR_ID=20$
                break;
            }
            case 21 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_ADD_CHARGES_WC.getOldValue()));//$JR_EXPR_ID=21$
                break;
            }
            case 22 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_MINUS_CHARGES_WC.getOldValue()));//$JR_EXPR_ID=22$
                break;
            }
            case 23 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_TOTAL_AMT.getOldValue()).add( ((java.math.BigDecimal)field_MINUS_CHARGES_WC.getOldValue()) ));//$JR_EXPR_ID=23$
                break;
            }
            case 24 : 
            {
                value = (java.math.BigDecimal)(( ((java.math.BigDecimal)field_ADD_CHARGES_WC.getOldValue())==null ? new java.math.BigDecimal(0) : ((java.math.BigDecimal)field_ADD_CHARGES_WC.getOldValue()) ));//$JR_EXPR_ID=24$
                break;
            }
            case 25 : 
            {
                value = (java.math.BigDecimal)(( ((java.math.BigDecimal)field_MINUS_CHARGES_WC.getOldValue())==null ? new java.math.BigDecimal(0) : ((java.math.BigDecimal)field_MINUS_CHARGES_WC.getOldValue()) ));//$JR_EXPR_ID=25$
                break;
            }
            case 26 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_TOTAL_AMT.getOldValue()));//$JR_EXPR_ID=26$
                break;
            }
            case 27 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_TOTAL_AMT.getOldValue()));//$JR_EXPR_ID=27$
                break;
            }
            case 28 : 
            {
                value = (java.lang.Object)(((java.math.BigDecimal)field_BENEFICIARY_TYPE_ID.getOldValue()));//$JR_EXPR_ID=28$
                break;
            }
            case 29 : 
            {
                value = (java.lang.String)(((java.lang.String)field_ben_type_desc.getOldValue()));//$JR_EXPR_ID=29$
                break;
            }
            case 30 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_type_collection.getOldValue()));//$JR_EXPR_ID=30$
                break;
            }
            case 31 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_type_demand.getOldValue()));//$JR_EXPR_ID=31$
                break;
            }
            case 32 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_type_qty.getOldValue()));//$JR_EXPR_ID=32$
                break;
            }
            case 33 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_type_collection_add.getOldValue()));//$JR_EXPR_ID=33$
                break;
            }
            case 34 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_type_collection_net.getOldValue()).add(((java.math.BigDecimal)variable_type_collection_sub.getOldValue())));//$JR_EXPR_ID=34$
                break;
            }
            case 35 : 
            {
                value = (java.lang.String)(((java.lang.String)field_ben_type_desc.getOldValue()) +" Total");//$JR_EXPR_ID=35$
                break;
            }
            case 36 : 
            {
                value = (java.lang.Object)(((java.math.BigDecimal)field_BENSO.getOldValue()));//$JR_EXPR_ID=36$
                break;
            }
            case 37 : 
            {
                value = (java.lang.String)(((java.lang.String)field_BENEFICIARY_NAME.getOldValue())+"("+ ((java.math.BigDecimal)field_BENSO.getOldValue())+")");//$JR_EXPR_ID=37$
                break;
            }
            case 38 : 
            {
                value = (java.lang.Boolean)(new Boolean (!((java.lang.String)parameter_count.getValue()).equals("1")));//$JR_EXPR_ID=38$
                break;
            }
            case 39 : 
            {
                value = (java.lang.Boolean)(new Boolean (!((java.lang.String)parameter_count.getValue()).equals("1")));//$JR_EXPR_ID=39$
                break;
            }
            case 40 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_office_name.getValue()));//$JR_EXPR_ID=40$
                break;
            }
            case 41 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_mvalue.getValue()));//$JR_EXPR_ID=41$
                break;
            }
            case 42 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_dd.getOldValue()));//$JR_EXPR_ID=42$
                break;
            }
            case 43 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_TOTAL_AMT.getOldValue()).add(((java.math.BigDecimal)field_MINUS_CHARGES_WC.getOldValue())));//$JR_EXPR_ID=43$
                break;
            }
            case 44 : 
            {
                value = (java.lang.Boolean)(new Boolean (!((java.lang.String)parameter_count.getValue()).equals("1")));//$JR_EXPR_ID=44$
                break;
            }
            case 45 : 
            {
                value = (java.lang.String)(((java.lang.String)field_mval.getOldValue()));//$JR_EXPR_ID=45$
                break;
            }
            case 46 : 
            {
                value = (java.lang.Boolean)(new Boolean (!((java.lang.String)parameter_count.getValue()).equals("1")));//$JR_EXPR_ID=46$
                break;
            }
            case 47 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_year.getOldValue()));//$JR_EXPR_ID=47$
                break;
            }
            case 48 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_qty.getOldValue()));//$JR_EXPR_ID=48$
                break;
            }
            case 49 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_ADD_CHARGES_WC.getOldValue()));//$JR_EXPR_ID=49$
                break;
            }
            case 50 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_tot.getOldValue()));//$JR_EXPR_ID=50$
                break;
            }
            case 51 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_net_collection.getOldValue()));//$JR_EXPR_ID=51$
                break;
            }
            case 52 : 
            {
                value = (java.lang.String)("Grand Total");//$JR_EXPR_ID=52$
                break;
            }
            case 53 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_net_demand.getOldValue()));//$JR_EXPR_ID=53$
                break;
            }
            case 54 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_net_qty.getOldValue()));//$JR_EXPR_ID=54$
                break;
            }
            case 55 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_net_collection_1.getOldValue()));//$JR_EXPR_ID=55$
                break;
            }
            case 56 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_net_collection_net.getOldValue()).add(((java.math.BigDecimal)variable_net_collection_2.getOldValue())));//$JR_EXPR_ID=56$
                break;
            }
            case 57 : 
            {
                value = (java.lang.Object)(((java.lang.String)parameter_office_id.getValue()));//$JR_EXPR_ID=57$
                break;
            }
            case 58 : 
            {
                value = (java.lang.Object)(((java.lang.String)parameter_month1.getValue()));//$JR_EXPR_ID=58$
                break;
            }
            case 59 : 
            {
                value = (java.lang.Object)(((java.lang.String)parameter_office_name.getValue()));//$JR_EXPR_ID=59$
                break;
            }
            case 60 : 
            {
                value = (java.lang.Object)(((java.lang.String)parameter_month2.getValue()));//$JR_EXPR_ID=60$
                break;
            }
            case 61 : 
            {
                value = (java.lang.Object)(((java.lang.String)parameter_ctxpath.getValue()));//$JR_EXPR_ID=61$
                break;
            }
            case 62 : 
            {
                value = (java.lang.Object)(((java.lang.String)parameter_count.getValue()));//$JR_EXPR_ID=62$
                break;
            }
            case 63 : 
            {
                value = (java.lang.Object)(((java.lang.String)parameter_mvalue.getValue()));//$JR_EXPR_ID=63$
                break;
            }
            case 64 : 
            {
                value = (java.lang.Object)(((java.lang.Integer)parameter_days.getValue()));//$JR_EXPR_ID=64$
                break;
            }
            case 65 : 
            {
                value = (java.lang.Object)(((java.lang.String)parameter_SUBREPORT_DIR.getValue()));//$JR_EXPR_ID=65$
                break;
            }
            case 66 : 
            {
                value = (java.lang.Object)(((java.lang.String)parameter_year1.getValue()));//$JR_EXPR_ID=66$
                break;
            }
            case 67 : 
            {
                value = (java.lang.Object)(((java.lang.String)parameter_year2.getValue()));//$JR_EXPR_ID=67$
                break;
            }
            case 68 : 
            {
                value = (java.sql.Connection)(((java.sql.Connection)parameter_REPORT_CONNECTION.getValue()));//$JR_EXPR_ID=68$
                break;
            }
            case 69 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_ctxpath.getValue()) + "PMS_DCB_DMD_COLLECTION_SUM.jasper");//$JR_EXPR_ID=69$
                break;
            }
           default :
           {
           }
        }
        
        return value;
    }


    /**
     *
     */
    public Object evaluateEstimated(int id) throws Throwable
    {
        Object value = null;

        switch (id)
        {
            case 0 : 
            {
                value = (java.lang.String)("D:\\NIC Source\\twadonline\\WebContent\\WEB-INF\\ReportSrc\\");//$JR_EXPR_ID=0$
                break;
            }
            case 1 : 
            {
                value = (java.lang.Integer)(new Integer(1));//$JR_EXPR_ID=1$
                break;
            }
            case 2 : 
            {
                value = (java.lang.Integer)(new Integer(1));//$JR_EXPR_ID=2$
                break;
            }
            case 3 : 
            {
                value = (java.lang.Integer)(new Integer(1));//$JR_EXPR_ID=3$
                break;
            }
            case 4 : 
            {
                value = (java.lang.Integer)(new Integer(0));//$JR_EXPR_ID=4$
                break;
            }
            case 5 : 
            {
                value = (java.lang.Integer)(new Integer(1));//$JR_EXPR_ID=5$
                break;
            }
            case 6 : 
            {
                value = (java.lang.Integer)(new Integer(0));//$JR_EXPR_ID=6$
                break;
            }
            case 7 : 
            {
                value = (java.lang.Integer)(new Integer(1));//$JR_EXPR_ID=7$
                break;
            }
            case 8 : 
            {
                value = (java.lang.Integer)(new Integer(0));//$JR_EXPR_ID=8$
                break;
            }
            case 9 : 
            {
                value = (java.lang.Integer)(new Integer(1));//$JR_EXPR_ID=9$
                break;
            }
            case 10 : 
            {
                value = (java.lang.Integer)(new Integer(0));//$JR_EXPR_ID=10$
                break;
            }
            case 11 : 
            {
                value = (java.lang.Integer)(new Integer(1));//$JR_EXPR_ID=11$
                break;
            }
            case 12 : 
            {
                value = (java.lang.Integer)(new Integer(0));//$JR_EXPR_ID=12$
                break;
            }
            case 13 : 
            {
                value = (java.lang.Integer)(((java.lang.Integer)variable_REPORT_COUNT.getEstimatedValue()));//$JR_EXPR_ID=13$
                break;
            }
            case 14 : 
            {
                value = (java.lang.Object)(((java.lang.Integer)variable_REPORT_COUNT.getEstimatedValue()));//$JR_EXPR_ID=14$
                break;
            }
            case 15 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_dd.getValue()));//$JR_EXPR_ID=15$
                break;
            }
            case 16 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_dd.getValue()));//$JR_EXPR_ID=16$
                break;
            }
            case 17 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_tot.getValue()));//$JR_EXPR_ID=17$
                break;
            }
            case 18 : 
            {
                value = (java.math.BigDecimal)(( ((java.math.BigDecimal)field_tot.getValue())==null ? new java.math.BigDecimal(0) : ((java.math.BigDecimal)field_tot.getValue())));//$JR_EXPR_ID=18$
                break;
            }
            case 19 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_qty.getValue()));//$JR_EXPR_ID=19$
                break;
            }
            case 20 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_qty.getValue()));//$JR_EXPR_ID=20$
                break;
            }
            case 21 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_ADD_CHARGES_WC.getValue()));//$JR_EXPR_ID=21$
                break;
            }
            case 22 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_MINUS_CHARGES_WC.getValue()));//$JR_EXPR_ID=22$
                break;
            }
            case 23 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_TOTAL_AMT.getValue()).add( ((java.math.BigDecimal)field_MINUS_CHARGES_WC.getValue()) ));//$JR_EXPR_ID=23$
                break;
            }
            case 24 : 
            {
                value = (java.math.BigDecimal)(( ((java.math.BigDecimal)field_ADD_CHARGES_WC.getValue())==null ? new java.math.BigDecimal(0) : ((java.math.BigDecimal)field_ADD_CHARGES_WC.getValue()) ));//$JR_EXPR_ID=24$
                break;
            }
            case 25 : 
            {
                value = (java.math.BigDecimal)(( ((java.math.BigDecimal)field_MINUS_CHARGES_WC.getValue())==null ? new java.math.BigDecimal(0) : ((java.math.BigDecimal)field_MINUS_CHARGES_WC.getValue()) ));//$JR_EXPR_ID=25$
                break;
            }
            case 26 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_TOTAL_AMT.getValue()));//$JR_EXPR_ID=26$
                break;
            }
            case 27 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_TOTAL_AMT.getValue()));//$JR_EXPR_ID=27$
                break;
            }
            case 28 : 
            {
                value = (java.lang.Object)(((java.math.BigDecimal)field_BENEFICIARY_TYPE_ID.getValue()));//$JR_EXPR_ID=28$
                break;
            }
            case 29 : 
            {
                value = (java.lang.String)(((java.lang.String)field_ben_type_desc.getValue()));//$JR_EXPR_ID=29$
                break;
            }
            case 30 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_type_collection.getEstimatedValue()));//$JR_EXPR_ID=30$
                break;
            }
            case 31 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_type_demand.getEstimatedValue()));//$JR_EXPR_ID=31$
                break;
            }
            case 32 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_type_qty.getEstimatedValue()));//$JR_EXPR_ID=32$
                break;
            }
            case 33 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_type_collection_add.getEstimatedValue()));//$JR_EXPR_ID=33$
                break;
            }
            case 34 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_type_collection_net.getEstimatedValue()).add(((java.math.BigDecimal)variable_type_collection_sub.getEstimatedValue())));//$JR_EXPR_ID=34$
                break;
            }
            case 35 : 
            {
                value = (java.lang.String)(((java.lang.String)field_ben_type_desc.getValue()) +" Total");//$JR_EXPR_ID=35$
                break;
            }
            case 36 : 
            {
                value = (java.lang.Object)(((java.math.BigDecimal)field_BENSO.getValue()));//$JR_EXPR_ID=36$
                break;
            }
            case 37 : 
            {
                value = (java.lang.String)(((java.lang.String)field_BENEFICIARY_NAME.getValue())+"("+ ((java.math.BigDecimal)field_BENSO.getValue())+")");//$JR_EXPR_ID=37$
                break;
            }
            case 38 : 
            {
                value = (java.lang.Boolean)(new Boolean (!((java.lang.String)parameter_count.getValue()).equals("1")));//$JR_EXPR_ID=38$
                break;
            }
            case 39 : 
            {
                value = (java.lang.Boolean)(new Boolean (!((java.lang.String)parameter_count.getValue()).equals("1")));//$JR_EXPR_ID=39$
                break;
            }
            case 40 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_office_name.getValue()));//$JR_EXPR_ID=40$
                break;
            }
            case 41 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_mvalue.getValue()));//$JR_EXPR_ID=41$
                break;
            }
            case 42 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_dd.getValue()));//$JR_EXPR_ID=42$
                break;
            }
            case 43 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_TOTAL_AMT.getValue()).add(((java.math.BigDecimal)field_MINUS_CHARGES_WC.getValue())));//$JR_EXPR_ID=43$
                break;
            }
            case 44 : 
            {
                value = (java.lang.Boolean)(new Boolean (!((java.lang.String)parameter_count.getValue()).equals("1")));//$JR_EXPR_ID=44$
                break;
            }
            case 45 : 
            {
                value = (java.lang.String)(((java.lang.String)field_mval.getValue()));//$JR_EXPR_ID=45$
                break;
            }
            case 46 : 
            {
                value = (java.lang.Boolean)(new Boolean (!((java.lang.String)parameter_count.getValue()).equals("1")));//$JR_EXPR_ID=46$
                break;
            }
            case 47 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_year.getValue()));//$JR_EXPR_ID=47$
                break;
            }
            case 48 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_qty.getValue()));//$JR_EXPR_ID=48$
                break;
            }
            case 49 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_ADD_CHARGES_WC.getValue()));//$JR_EXPR_ID=49$
                break;
            }
            case 50 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_tot.getValue()));//$JR_EXPR_ID=50$
                break;
            }
            case 51 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_net_collection.getEstimatedValue()));//$JR_EXPR_ID=51$
                break;
            }
            case 52 : 
            {
                value = (java.lang.String)("Grand Total");//$JR_EXPR_ID=52$
                break;
            }
            case 53 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_net_demand.getEstimatedValue()));//$JR_EXPR_ID=53$
                break;
            }
            case 54 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_net_qty.getEstimatedValue()));//$JR_EXPR_ID=54$
                break;
            }
            case 55 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_net_collection_1.getEstimatedValue()));//$JR_EXPR_ID=55$
                break;
            }
            case 56 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_net_collection_net.getEstimatedValue()).add(((java.math.BigDecimal)variable_net_collection_2.getEstimatedValue())));//$JR_EXPR_ID=56$
                break;
            }
            case 57 : 
            {
                value = (java.lang.Object)(((java.lang.String)parameter_office_id.getValue()));//$JR_EXPR_ID=57$
                break;
            }
            case 58 : 
            {
                value = (java.lang.Object)(((java.lang.String)parameter_month1.getValue()));//$JR_EXPR_ID=58$
                break;
            }
            case 59 : 
            {
                value = (java.lang.Object)(((java.lang.String)parameter_office_name.getValue()));//$JR_EXPR_ID=59$
                break;
            }
            case 60 : 
            {
                value = (java.lang.Object)(((java.lang.String)parameter_month2.getValue()));//$JR_EXPR_ID=60$
                break;
            }
            case 61 : 
            {
                value = (java.lang.Object)(((java.lang.String)parameter_ctxpath.getValue()));//$JR_EXPR_ID=61$
                break;
            }
            case 62 : 
            {
                value = (java.lang.Object)(((java.lang.String)parameter_count.getValue()));//$JR_EXPR_ID=62$
                break;
            }
            case 63 : 
            {
                value = (java.lang.Object)(((java.lang.String)parameter_mvalue.getValue()));//$JR_EXPR_ID=63$
                break;
            }
            case 64 : 
            {
                value = (java.lang.Object)(((java.lang.Integer)parameter_days.getValue()));//$JR_EXPR_ID=64$
                break;
            }
            case 65 : 
            {
                value = (java.lang.Object)(((java.lang.String)parameter_SUBREPORT_DIR.getValue()));//$JR_EXPR_ID=65$
                break;
            }
            case 66 : 
            {
                value = (java.lang.Object)(((java.lang.String)parameter_year1.getValue()));//$JR_EXPR_ID=66$
                break;
            }
            case 67 : 
            {
                value = (java.lang.Object)(((java.lang.String)parameter_year2.getValue()));//$JR_EXPR_ID=67$
                break;
            }
            case 68 : 
            {
                value = (java.sql.Connection)(((java.sql.Connection)parameter_REPORT_CONNECTION.getValue()));//$JR_EXPR_ID=68$
                break;
            }
            case 69 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_ctxpath.getValue()) + "PMS_DCB_DMD_COLLECTION_SUM.jasper");//$JR_EXPR_ID=69$
                break;
            }
           default :
           {
           }
        }
        
        return value;
    }


}
